# Введение в машинное обучение, АБД

## НИУ ВШЭ, 2025-26 учебный год

# Бонусное домашнее задание. Модели классификации и регрессии

Задание выполнил(а):

Явнова Софья

## Общая информация

__Внимание!__  

Домашнее задание выполняется самостоятельно. Не допускается помощь в решении домашнего задания от однокурсников или третьих лиц. «Похожие» решения считаются плагиатом, и все задействованные студенты — в том числе и те, у кого списали, — не могут получить за него больше 0 баллов. Использование в решении домашнего задания генеративных моделей (ChatGPT и так далее) за рамками справочной и образовательной информации для генерации кода задания — считается плагиатом, и такое домашнее задание оценивается в 0 баллов.

Прежде чем проверять задания:
- **Перезапустите ядро** (**restart the kernel**) (В меню, выбрать Ядро (Kernel) $\rightarrow$ Перезапустить (Restart)
- Затем **Выполнить все ячейки**  **run all cells** (В меню, выбрать Ячейка (Cell) $\rightarrow$ Запустить все (Run All).

Убедитесь, что заполнены все ячейки с комментарием "НАЧАЛО ВАШЕГО РЕШЕНИЯ".

После ячеек с заданием следуют ячейки с проверкой с помощью assert.

Если в коде есть ошибки, assert выведет уведомление об ошибке.

Если в коде нет ошибок, assert отработает без вывода дополнительной информации.

---

## Цель задания

В этом ноутбуке мы на практике закрепим работу с алгоритмами регрессии и классификации.

В задании необходимо имплементировать `8` моделей регрессии и `7` моделей классификации, а также подобрать к этим моделям оптимальные параметры с помощью `GridSearchCV`.

Scikit-learn (sklearn) и ряд других библиотек предлагают множество алгоритмов регрессии, которые можно использовать для решения задач прогнозирования численных значений. Вот некоторые из наиболее популярных алгоритмов регрессии:

1. Линейная регрессия (Linear Regression): `sklearn.linear_model.LinearRegression`
   - Простая модель, основанная на линейной комбинации признаков.
   - Подходит для задач с линейной зависимостью между признаками и целевой переменной.

2. Регрессия LASSO (LASSO Regression): `sklearn.linear_model.Lasso`
   - Линейная модель, которая также выполняет регуляризацию L1 (L1 regularization).
   - Помогает в выборе наиболее важных признаков и обеспечивает разреженность весов.

3. Регрессия Ridge (Ridge Regression): `sklearn.linear_model.Ridge`
   - Линейная модель, которая выполняет регуляризацию L2 (L2 regularization).
   - Помогает в уменьшении эффекта мультиколлинеарности и контролирует значения весов.

4. ElasticNet регрессия (ElasticNet Regression): `sklearn.linear_model.ElasticNet`
   - Комбинация регрессии LASSO и регрессии Ridge.
   - Обеспечивает баланс между отбором признаков и контролем мультиколлинеарности.

5. Регрессия по методу опорных векторов (Support Vector Regression): `sklearn.svm.SVR`
   - Расширение метода опорных векторов для задачи регрессии.
   - Позволяет работать с нелинейными зависимостями с помощью ядерных функций.

6. Решающие деревья (Decision Trees): `sklearn.tree.DecisionTreeRegressor`
   - Модель, основанная на деревьях принятия решений.
   - Позволяет обрабатывать нелинейные зависимости и автоматически выбирать наиболее важные признаки.

7. Случайный лес (Random Forest): `sklearn.ensemble.RandomForestRegressor`
   - Ансамблевая модель, состоящая из множества решающих деревьев.
   - Объединяет прогнозы множества деревьев для улучшения обобщающей способности.

8. Градиентный бустинг (Gradient Boosting): `sklearn.ensemble.GradientBoostingRegressor`
   - Ансамблевая модель, которая строит ансамбль слабых моделей в итеративном режиме.
   - Каждая новая модель исправляет ошибки предыдущих моделей, улучшая предсказания.

9. AdaBoost (Adaptive Boosting): `sklearn.ensemble.AdaBoostRegressor`
   - Алгоритм адаптивного бустинга, который взвешивает обучающие примеры для создания модели.
   - Фокусируется на примерах с большими ошибками для их исправления.

10. XGBoost: `xgboost.XGBRegressor`
    - Библиотека с открытым исходным кодом, предоставляющая градиентный бустинг.
    - Позволяет эффективно обрабатывать большие наборы данных и достигать высокой точности.

11. LightGBM: `lightgbm.LGBMRegressor`
    - Библиотека с открытым исходным кодом, предоставляющая градиентный бустинг.
    - Ориентирована на эффективность и скорость работы с большими объемами данных.

12. CatBoost: `catboost.CatBoostRegressor`
    - Библиотека с открытым исходным кодом, предоставляющая градиентный бустинг.
    - Обладает встроенной поддержкой категориальных признаков и автоматическим кодированием.
    
Некоторые из наиболее популярных алгоритмов классификации:

1. K-ближайших соседей (K-Nearest Neighbors): `sklearn.neighbors.KNeighborsClassifier`
   - Алгоритм, который классифицирует объекты на основе ближайших соседей в пространстве признаков.
   - Основывается на значении классов соседей для принятия решения о классификации.

2. Логистическая регрессия (Logistic Regression): `sklearn.linear_model.LogisticRegression`
   - Классификационная модель, которая использует логистическую функцию для предсказания вероятности принадлежности к классам.
   - Часто используется в задачах бинарной классификации.
   
3. Наивный Байес (Naive Bayes): `sklearn.naive_bayes.GaussianNB` (для непрерывных признаков) или `sklearn.naive_bayes.MultinomialNB` (для дискретных признаков)
   - Вероятностный классификатор, основанный на применении теоремы Байеса с предположением о независимости признаков.
   - Хорошо работает с наборами данных с большим числом признаков и предположением о независимости признаков.

4. Метод опорных векторов (Support Vector Machines): `sklearn.svm.SVC`
   - Алгоритм, который строит гиперплоскость или набор гиперплоскостей в многомерном пространстве для классификации объектов.
   - Может обрабатывать нелинейные зависимости с помощью ядерных функций.

5. Решающие деревья (Decision Trees): `sklearn.tree.DecisionTreeClassifier`
   - Модель, основанная на деревьях принятия решений.
   - Позволяет обрабатывать нелинейные зависимости и автоматически выбирать наиболее важные признаки.

6. Случайный лес (Random Forest): `sklearn.ensemble.RandomForestClassifier`
   - Ансамблевая модель, состоящая из множества решающих деревьев.
   - Объединяет прогнозы множества деревьев для улучшения обобщающей способности.

7. Градиентный бустинг (Gradient Boosting): `sklearn.ensemble.GradientBoostingClassifier`
   - Ансамблевая модель, которая строит ансамбль слабых моделей в итеративном режиме.
   - Каждая новая модель исправляет ошибки предыдущих моделей, улучшая предсказания.

8. AdaBoost (Adaptive Boosting): `sklearn.ensemble.AdaBoostClassifier`
   - Алгоритм адаптивного бустинга, который взвешивает обучающие примеры для создания модели.
   - Фокусируется на примерах с большими ошибками для их исправления.

9. XGBoost: `xgboost.XGBClassifier`
   - Библиотека с открытым исходным кодом, предоставляющая градиентный бустинг для классификации.
   - Позволяет эффективно обрабатывать большие наборы данных и достигать высокой точности.

10. LightGBM: `lightgbm.LGBMClassifier`
    - Библиотека с открытым исходным кодом, предоставляющая градиентный бустинг для классификации.
    - Ориентирована на эффективность и скорость работы с большими объемами данных.

11. CatBoost: `catboost.CatBoostClassifier`
    - Библиотека с открытым исходным кодом, предоставляющая градиентный бустинг для классификации.
    - Обладает встроенной поддержкой категориальных признаков и автоматическим кодированием.

Это некоторые из алгоритмов, доступных в scikit-learn и других библиотеках. Каждый алгоритм имеет свои особенности и подходит для разных типов данных и задач. Вам следует экспериментировать с разными алгоритмами и настраивать их параметры для достижения наилучших результатов в конкретной задаче.

При решении данного задания потребуются следующие библиотеки:
- pandas
- numpy
- sklearn
- xgboost
- catboost

Установить их можно следующим образом:
- pip install pandas==2.0.0
- pip install numpy==1.24.0
- pip install scikit-learn==1.2.0
- pip install xgboost==1.7.5
- pip install catboost==1.2

# Задача регрессии

Датасет "Boston" является одним из классических наборов данных. Он представляет собой набор данных, связанных с ценами на жилье в Бостоне, Массачусетс, США. Этот набор данных широко используется в задачах регрессии и демонстрирует взаимосвязь между различными факторами и стоимостью жилья.

Описание признаков (признаки ниже представлены в формате "название признака (тип данных)"):
1. CRIM (float): уровень преступности на душу населения по городам.
2. ZN (float): доля жилой земли, зонированной для участков более 25 000 кв.фут.
3. INDUS (float): доля нерозничных площадей на город.
4. CHAS (integer): Данный признак является фиктивной переменной, представляющей наличие или отсутствие ограничения участка жилья рекой Charles River.
5. NOX (float): концентрация оксидов азота (частей на 10 миллионов).
6. RM (float): среднее количество комнат в жилом помещении.
7. AGE (float): доля занятых владельцами единиц, построенных до 1940 года.
8. DIS (float): взвешенные расстояния до пяти бостонских центров занятости.
9. RAD (integer): индекс доступности к радиальным магистралям.
10. TAX (integer): полная ставка налога на имущество на 10 000 долларов США.
11. PTRATIO (float): соотношение учеников и учителей по городам.
12. B (float): 1000 * (Bk - 0.63) ^ 2, где Bk - доля чернокожего населения по городам.
13. LSTAT (float): процент более низкого статуса населения.
14. MEDV (float): медианная стоимость домов, занимаемых владельцами, в тысячах долларов.

Целевая переменная (выходной признак):
- MEDV: медианная стоимость домов, занимаемых владельцами, в тысячах долларов.

Цель состоит в том, чтобы предсказать медианную стоимость жилья на основе доступных признаков. Этот набор данных часто используется для задачи регрессии и оценки моделей машинного обучения на основе различных признаков, связанных с жильем.

Мы будем использовать 8 моделей регрессии и GridSearchCV для подбора параметров:
1. Линейная регрессия (Linear Regression): `sklearn.linear_model.LinearRegression`
2. Регрессия по методу опорных векторов (Support Vector Regression): `sklearn.svm.SVR`
3. Решающие деревья (Decision Trees): `sklearn.tree.DecisionTreeRegressor`
4. Случайный лес (Random Forest): `sklearn.ensemble.RandomForestRegressor`
5. Градиентный бустинг (Gradient Boosting): `sklearn.ensemble.GradientBoostingRegressor`
6. AdaBoost (Adaptive Boosting): `sklearn.ensemble.AdaBoostRegressor`
7. XGBoost: `xgboost.XGBRegressor`
8. CatBoost: `catboost.CatBoostRegressor`

In [ ]:
%%capture
!pip install catboost

In [40]:
import pandas as pd
import numpy as np
import time

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error
from sklearn.metrics import f1_score

import xgboost as xgb
import catboost as cb

import warnings
warnings.filterwarnings("ignore")

In [ ]:
# Загрузка данных из CSV файла
data = pd.read_csv("https://www.dropbox.com/scl/fi/ipky49nzyhj5ye9nkotdd/boston.csv?rlkey=r1weqyykdahgop5sl7rv01e2t&dl=1", delimiter=",")
data.head()

,CRIM,ZN,INDUS,CHAS,NX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [ ]:
# Разделение на признаки (X) и целевую переменную (y)
X = data.drop('MEDV', axis=1)
y = data['MEDV']


# Разделение на обучающий и тестовый наборы данных
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Определение препроцессора для категориальных и числовых признаков
categorical_features = ['RAD']
categorical_transformer = OneHotEncoder(handle_unknown='ignore')
numerical_features = X_train.select_dtypes(include=['int64', 'float64']).columns
numerical_transformer = StandardScaler()

# Объединение препроцессоров
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_features),
        ('num', numerical_transformer, numerical_features)
    ])

# Создание пайплайна для препроцессора
preprocessing_pipeline = Pipeline(steps=[('preprocessor', preprocessor)])

# Применение препроцессора к данным
X_train = preprocessing_pipeline.fit_transform(X_train)
X_test = preprocessing_pipeline.transform(X_test)

In [ ]:
from sklearn.linear_model import LinearRegression

"""
Задание 1.1 (1 балл)
Сохраните в переменную model экземпляр класса LinearRegression без параметров.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ
model = LinearRegression()
#raise NotImplementedError()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""
'fit_intercept' определяет, должна ли модель оценивать коэффициент смещения (пересечения) или нет.
Если fit_intercept=True, модель будет оценивать коэффициент смещения, то есть точку, где линейная
функция пересекает ось зависимой переменной (y-ось). Если fit_intercept=False, модель будет проходить
через начало координат (0, 0), и коэффициент смещения будет равен нулю.
"""
params = {'fit_intercept': [True, False]}

# Создание объекта GridSearchCV
"""
Задание 1.2 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='neg_mean_squared_error'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='neg_mean_squared_error')

#raise NotImplementedError()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ


# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров LinearRegression
LinearRegression_best_params = grid_search.best_params_
print("LinearRegression_best_params: ", LinearRegression_best_params)

# Вычисление MSE
LinearRegression_mse = mean_squared_error(y_test, y_pred)
print("LinearRegression_mse: ", LinearRegression_mse)

LinearRegression_best_params:  {'fit_intercept': True}
LinearRegression_mse:  24.818442738481327

In [ ]:
assert type(model) == LinearRegression
assert type(grid_search) == GridSearchCV

In [ ]:
from sklearn.svm import SVR

"""
Задание 1.3 (1 балл)
Сохраните в переменную model экземпляр класса SVR без параметров.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model = SVR()
#raise NotImplementedError()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""
Описание параметров:

1. `'C'` - параметр регуляризации (также известный как параметр сложности),
    контролирует штраф за ошибки модели. Он определяет, насколько модель будет учитывать ошибки в данных
    при подгонке к обучающим примерам. Значения `[0.1, 1, 10]` представляют различные величины штрафа.
    Более высокое значение C соответствует меньшему штрафу, что позволяет модели более гибко подгоняться к
    данным и учитывать даже сложные шаблоны. Низкое значение C, напротив, приводит к более сильному штрафу
    и более простой модели.

2. `'kernel'` - параметр, определяющий тип ядра, используемого в модели. Ядро определяет способ преобразования
    пространства признаков, что позволяет модели обрабатывать нелинейные зависимости между признаками и целевой
    переменной. Значения `['linear', 'rbf', 'poly']` определяют различные типы ядер:
   - `'linear'` - линейное ядро, применяет линейное преобразование и подходит для линейно разделимых данных.
   - `'rbf'` (радиально-базисное функциональное ядро) - нелинейное ядро, которое преобразует данные в более
   высокие размерности, используя радиально-базисную функцию. Оно хорошо подходит для обработки нелинейных
   зависимостей и может быть эффективным в случаях, когда данные не являются линейно разделимыми.
   - `'poly'` (полиномиальное ядро) - преобразует данные в пространство более высокой размерности с
   использованием полиномиальной функции. Полиномиальное ядро может обрабатывать нелинейные зависимости,
   особенно в случаях, когда данные имеют несколько признаков.

3. `'gamma'` - параметр ядра, контролирующий влияние каждого обучающего примера на формирование границы решения.
    Значения `['scale', 'auto']` определяют различные стратегии для выбора значения гаммы:
   - `'scale'` - значение гаммы рассчитывается как обратное среднее значение расстояний между обучающими
       примерами.
   - `'auto'` - значение гаммы рассчитывается как обратное численное значение признаков.
"""
params = {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf', 'poly'], 'gamma': ['scale', 'auto']}

# Создание объекта GridSearchCV
"""
Задание 1.4 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='neg_mean_squared_error'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='neg_mean_squared_error')
# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров LinearRegression
SVR_best_params = grid_search.best_params_
print("SVR_best_params: ", SVR_best_params)

# Вычисление MSE
SVR_mse = mean_squared_error(y_test, y_pred)
print("SVR_mse: ", SVR_mse)

SVR_best_params:  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
SVR_mse:  13.497844888204211

In [ ]:
assert type(model) == SVR
assert type(grid_search) == GridSearchCV

In [ ]:
from sklearn.tree import DecisionTreeRegressor

"""
Задание 1.5 (1 балл)
Сохраните в переменную model экземпляр класса DecisionTreeRegressor без параметров.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model = DecisionTreeRegressor()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""
'max_depth' определяет максимальную глубину дерева решений.
Более высокое значение max_depth позволяет модели создавать более сложные правила,
что может привести к переобучению. Значения [None, 5, 10] представляют
различные значения максимальной глубины дерева.
"""
params = {'max_depth': [None, 5, 10]}

# Создание объекта GridSearchCV
"""
Задание 1.6 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='neg_mean_squared_error'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='neg_mean_squared_error')

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров LinearRegression
DecisionTreeRegressor_best_params = grid_search.best_params_
print("DecisionTreeRegressor_best_params: ", DecisionTreeRegressor_best_params)

# Вычисление MSE
DecisionTreeRegressor_mse = mean_squared_error(y_test, y_pred)
print("DecisionTreeRegressor_mse: ", DecisionTreeRegressor_mse)

DecisionTreeRegressor_best_params:  {'max_depth': None}
DecisionTreeRegressor_mse:  9.984117647058822

In [ ]:
assert type(model) == DecisionTreeRegressor
assert type(grid_search) == GridSearchCV

In [ ]:
from sklearn.ensemble import RandomForestRegressor

# Создание объекта RandomForestRegressor
"""
Задание 1.7 (1 балл)
Сохраните в переменную model экземпляр класса RandomForestRegressor без параметров.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model = RandomForestRegressor()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""
- `n_estimators`: Это количество деревьев в случайном лесу. Определяет, сколько деревьев будет
использоваться для построения ансамбля. Значение по умолчанию - 100. Увеличение значения может
улучшить производительность модели, но с увеличением числа деревьев возрастает время обучения и
предсказания. Обычно выбирают значения в диапазоне от 100 до 1000.

- `max_depth`: Максимальная глубина каждого дерева в лесу. Ограничивает количество уровней в дереве.
Значение `None` означает, что глубина деревьев не ограничена. Значение по умолчанию - `None`.
Установка ограничения на глубину деревьев может помочь предотвратить переобучение модели. Обычно
выбирают значения в диапазоне от 5 до 10.

- `min_samples_split`: Минимальное количество образцов, необходимое для разделения внутреннего узла.
Определяет, сколько образцов должно быть в узле, чтобы он мог быть разделен на дочерние узлы.
Значение по умолчанию - 2. Увеличение значения может привести к более устойчивой модели и предотвратить
переобучение. Обычно выбирают значения в диапазоне от 2 до 10.
"""
params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10]
}

# Создание объекта GridSearchCV
"""
Задание 1.8 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='neg_mean_squared_error'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='neg_mean_squared_error')

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров RandomForestRegressor
RandomForestRegressor_best_params = grid_search.best_params_
print("RandomForestRegressor_best_params: ", RandomForestRegressor_best_params)

# Вычисление MSE
RandomForestRegressor_mse = mean_squared_error(y_test, y_pred)
print("RandomForestRegressor_mse: ", RandomForestRegressor_mse)

RandomForestRegressor_best_params:  {'max_depth': 10, 'min_samples_split': 2, 'n_estimators': 200}
RandomForestRegressor_mse:  8.572064308378026

In [ ]:
assert type(model) == RandomForestRegressor
assert type(grid_search) == GridSearchCV

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

# Создание объекта GradientBoostingRegressor
"""
Задание 1.9 (1 балл)
Сохраните в переменную model экземпляр класса GradientBoostingRegressor без параметров.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model = GradientBoostingRegressor()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""
n_estimators (int): Определяет количество деревьев в ансамбле. Чем больше значение n_estimators,
тем больше деревьев будет построено, и тем сложнее будет модель. Увеличение количества деревьев
может улучшить производительность модели, но может также привести к увеличению времени обучения и
потенциальному переобучению. В данном случае рассматриваются значения [100, 200, 300].

learning_rate (float): Определяет скорость обучения модели. Этот параметр контролирует вклад каждого
дерева в ансамбле. Более низкое значение learning_rate означает, что каждое дерево вносит меньший вклад
в предсказание и, следовательно, модель будет обучаться медленнее, но может быть более устойчива к
переобучению. В данном случае рассматриваются значения [0.1, 0.01, 0.001].

max_depth (int): Определяет максимальную глубину каждого дерева в ансамбле. Глубина дерева указывает,
сколько раз дерево будет делить данные на более мелкие группы. Увеличение глубины деревьев может
привести к более сложным моделям, которые лучше адаптируются к обучающим данным, но могут быть более
склонны к переобучению. В данном случае рассматриваются значения [3, 5, 10].
"""
params = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.1, 0.01, 0.001],
    'max_depth': [3, 5, 10]
}

# Создание объекта GridSearchCV
"""
Задание 1.10 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='neg_mean_squared_error'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ
grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='neg_mean_squared_error')
# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров GradientBoostingRegressor
GradientBoostingRegressor_best_params = grid_search.best_params_
print("GradientBoostingRegressor_best_params: ", GradientBoostingRegressor_best_params)

# Вычисление MSE
GradientBoostingRegressor_mse = mean_squared_error(y_test, y_pred)
print("GradientBoostingRegressor_mse: ", GradientBoostingRegressor_mse)

GradientBoostingRegressor_best_params:  {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}
GradientBoostingRegressor_mse:  6.498597264505265

In [ ]:
assert type(model) == GradientBoostingRegressor
assert type(grid_search) == GridSearchCV

In [ ]:
from sklearn.ensemble import AdaBoostRegressor

# Создание объекта AdaBoostRegressor
"""
Задание 1.11 (1 балл)
Сохраните в переменную model экземпляр класса AdaBoostRegressor без параметров.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model= AdaBoostRegressor()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ


# Определение параметров для GridSearchCV
"""
n_estimators: Этот параметр определяет количество базовых моделей (регрессоров), которые будут
использоваться в ансамбле AdaBoost. Базовая модель представляет собой слабый регрессор, например,
решающее дерево с ограниченной глубиной. Увеличение значения n_estimators может улучшить
производительность модели, но может также привести к более длительному времени обучения.
Обычно рекомендуется выбирать достаточно большое значение n_estimators, чтобы дать модели
достаточно базовых моделей для обучения, но при этом избегать переобучения.

learning_rate: Этот параметр контролирует вклад каждой базовой модели в окончательное предсказание.
Меньшее значение learning_rate означает, что каждая базовая модель вносит меньший вклад, что может
помочь улучшить обобщающую способность модели и уменьшить переобучение. Однако слишком низкое значение
learning_rate может привести к несоответствию модели с данными и, как следствие, к понижению
производительности. Обычно рекомендуется начинать с небольшого значения learning_rate и,
при необходимости, увеличивать его.
"""
params = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.1, 0.01, 0.001]
}

# Создание объекта GridSearchCV
"""
Задание 1.12 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='neg_mean_squared_error'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='neg_mean_squared_error')


# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров AdaBoostRegressor
AdaBoostRegressor_best_params = grid_search.best_params_
print("AdaBoostRegressor_best_params: ", AdaBoostRegressor_best_params)

# Вычисление MSE
AdaBoostRegressor_mse = mean_squared_error(y_test, y_pred)
print("AdaBoostRegressor_mse: ", AdaBoostRegressor_mse)

AdaBoostRegressor_best_params:  {'learning_rate': 0.1, 'n_estimators': 100}
AdaBoostRegressor_mse:  11.358523987100476

In [ ]:
assert type(model) == AdaBoostRegressor
assert type(grid_search) == GridSearchCV

In [ ]:
from xgboost import XGBRegressor

# Создание объекта XGBRegressor
"""
Задание 1.13 (1 балл)
Сохраните в переменную model экземпляр класса XGBRegressor без параметров.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model = XGBRegressor()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""
'n_estimators' определяет количество деревьев в ансамбле XGBoost. Большее значение n_estimators может
улучшить производительность модели, но при этом потребуется больше вычислительных ресурсов и время
обучения. Рекомендуется выбирать достаточно большое значение, но избегать переобучения.

'learning_rate' контролирует вклад каждого дерева в окончательное предсказание модели. Меньшее значение
learning_rate означает меньший вклад каждого дерева, что может помочь улучшить обобщающую способность
модели. Однако, слишком низкое значение может привести к недообучению модели.

'max_depth' определяет максимальную глубину каждого дерева в ансамбле. Большая глубина может помочь
модели захватить более сложные взаимодействия в данных, но также может привести к переобучению.
Рекомендуется начинать с небольшой глубины и постепенно увеличивать, контролируя производительность и
переобучение модели.
"""
params = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.1, 0.01, 0.001],
    'max_depth': [3, 5, 10]
}

# Создание объекта GridSearchCV
"""
Задание 1.14 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='neg_mean_squared_error'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='neg_mean_squared_error')

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров XGBRegressor
XGBRegressor_best_params = grid_search.best_params_
print("XGBRegressor_best_params: ", XGBRegressor_best_params)

# Вычисление MSE
XGBRegressor_mse = mean_squared_error(y_test, y_pred)
print("XGBRegressor_mse: ", XGBRegressor_mse)

XGBRegressor_best_params:  {'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}
XGBRegressor_mse:  5.988378570059145

In [ ]:
assert type(model) == XGBRegressor
assert type(grid_search) == GridSearchCV

In [ ]:
from catboost import CatBoostRegressor

# Создание объекта CatBoostRegressor
"""
Задание 1.15 (1 балл)
Сохраните в переменную model экземпляр класса CatBoostRegressor с параметром silent=True.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model =CatBoostRegressor()
# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""

learning_rate: Скорость обучения модели. Определяет вклад каждого дерева в композицию.
Меньшие значения обычно требуют большего числа деревьев для достижения хорошей производительности модели.

n_estimators: Количество деревьев в градиентном бустинге. Большее количество деревьев может улучшить
производительность модели, но также может привести к переобучению, поэтому следует подбирать
оптимальное значение.

max_depth: Максимальная глубина каждого дерева в градиентном бустинге. Большая глубина может увеличить
производительность модели, но также может привести к переобучению.

subsample: Доля обучающих примеров, используемых для обучения каждого дерева в градиентном бустинге.
Значение меньше 1.0 может помочь уменьшить переобучение.

colsample_bylevel: Доля признаков, используемых для обучения каждого уровня дерева в градиентном бустинге.
Значение меньше 1.0 может помочь уменьшить переобучение.

reg_lambda: Коэффициент L2-регуляризации для весов модели. Используется для сдерживания переобучения.
"""
params = {
    'learning_rate': [0.1, 0.01, 0.001],
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 10],
    'subsample': [1.0],
    'colsample_bylevel': [1.0],
    'reg_lambda': [3.0]
}

# Создание объекта GridSearchCV
"""
Задание 1.16 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='neg_mean_squared_error'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='neg_mean_squared_error')

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров CatBoostRegressor
CatBoostRegressor_best_params = grid_search.best_params_
print("CatBoostRegressor_best_params: ", CatBoostRegressor_best_params)

# Вычисление MSE
CatBoostRegressor_mse = mean_squared_error(y_test, y_pred)
print("CatBoostRegressor_mse: ", CatBoostRegressor_mse)

Streaming output truncated to the last 5000 lines.
2:	learn: 9.1454091	total: 1.61ms	remaining: 52.2ms
3:	learn: 9.1406067	total: 2.12ms	remaining: 50.9ms
4:	learn: 9.1355425	total: 2.59ms	remaining: 49.2ms
5:	learn: 9.1308516	total: 3.08ms	remaining: 48.3ms
6:	learn: 9.1261528	total: 3.55ms	remaining: 47.1ms
7:	learn: 9.1209336	total: 4.02ms	remaining: 46.3ms
8:	learn: 9.1158491	total: 4.47ms	remaining: 45.3ms
9:	learn: 9.1108007	total: 4.94ms	remaining: 44.5ms
10:	learn: 9.1061094	total: 5.42ms	remaining: 43.8ms
11:	learn: 9.1004955	total: 5.89ms	remaining: 43.2ms
12:	learn: 9.0953761	total: 6.34ms	remaining: 42.5ms
13:	learn: 9.0905497	total: 6.82ms	remaining: 41.9ms
14:	learn: 9.0863014	total: 7.29ms	remaining: 41.3ms
15:	learn: 9.0821481	total: 7.76ms	remaining: 40.7ms
16:	learn: 9.0774276	total: 8.21ms	remaining: 40.1ms
17:	learn: 9.0721637	total: 8.67ms	remaining: 39.5ms
18:	learn: 9.0675432	total: 9.11ms	remaining: 38.8ms
19:	learn: 9.0630024	total: 9.57ms	remaining: 38.3ms
20:	learn: 9.0592010	total: 10ms	remaining: 37.8ms
21:	learn: 9.0539200	total: 10.5ms	remaining: 37.3ms
22:	learn: 9.0497397	total: 11ms	remaining: 36.8ms
23:	learn: 9.0449946	total: 11.4ms	remaining: 36.2ms
24:	learn: 9.0406281	total: 11.9ms	remaining: 35.7ms
25:	learn: 9.0358309	total: 12.4ms	remaining: 35.2ms
26:	learn: 9.0311405	total: 12.8ms	remaining: 34.7ms
27:	learn: 9.0258443	total: 13.3ms	remaining: 34.2ms
28:	learn: 9.0215007	total: 13.8ms	remaining: 33.7ms
29:	learn: 9.0170325	total: 14.2ms	remaining: 33.2ms
30:	learn: 9.0119603	total: 14.7ms	remaining: 32.8ms
31:	learn: 9.0073686	total: 15.2ms	remaining: 32.2ms
32:	learn: 9.0018676	total: 15.7ms	remaining: 31.8ms
33:	learn: 8.9965192	total: 16.1ms	remaining: 31.3ms
34:	learn: 8.9918504	total: 16.6ms	remaining: 30.8ms
35:	learn: 8.9873882	total: 17.1ms	remaining: 30.3ms
36:	learn: 8.9817702	total: 17.5ms	remaining: 29.9ms
37:	learn: 8.9769518	total: 18ms	remaining: 29.4ms
38:	learn: 8.9716205	total: 18.5ms	remaining: 28.9ms
39:	learn: 8.9662508	total: 18.9ms	remaining: 28.4ms
40:	learn: 8.9609780	total: 19.4ms	remaining: 27.9ms
41:	learn: 8.9557076	total: 19.9ms	remaining: 27.4ms
42:	learn: 8.9512738	total: 20.3ms	remaining: 26.9ms
43:	learn: 8.9459141	total: 20.8ms	remaining: 26.4ms
44:	learn: 8.9408954	total: 21.2ms	remaining: 26ms
45:	learn: 8.9353588	total: 21.7ms	remaining: 25.5ms
46:	learn: 8.9302129	total: 22.2ms	remaining: 25ms
47:	learn: 8.9253253	total: 22.6ms	remaining: 24.5ms
48:	learn: 8.9207330	total: 23.1ms	remaining: 24ms
49:	learn: 8.9160297	total: 23.5ms	remaining: 23.5ms
50:	learn: 8.9110077	total: 24ms	remaining: 23.1ms
51:	learn: 8.9063433	total: 24.5ms	remaining: 22.6ms
52:	learn: 8.9011285	total: 24.9ms	remaining: 22.1ms
53:	learn: 8.8965203	total: 25.4ms	remaining: 21.6ms
54:	learn: 8.8908439	total: 25.9ms	remaining: 21.2ms
55:	learn: 8.8853723	total: 26.4ms	remaining: 20.7ms
56:	learn: 8.8809106	total: 26.9ms	remaining: 20.3ms
57:	learn: 8.8758983	total: 27.3ms	remaining: 19.8ms
58:	learn: 8.8703532	total: 27.8ms	remaining: 19.3ms
59:	learn: 8.8655477	total: 28.3ms	remaining: 18.9ms
60:	learn: 8.8606493	total: 28.7ms	remaining: 18.4ms
61:	learn: 8.8554597	total: 31.7ms	remaining: 19.4ms
62:	learn: 8.8509464	total: 32.5ms	remaining: 19.1ms
63:	learn: 8.8459393	total: 34.6ms	remaining: 19.5ms
64:	learn: 8.8410339	total: 35.7ms	remaining: 19.2ms
65:	learn: 8.8366773	total: 36.3ms	remaining: 18.7ms
66:	learn: 8.8321752	total: 36.9ms	remaining: 18.2ms
67:	learn: 8.8282017	total: 38.1ms	remaining: 17.9ms
68:	learn: 8.8228207	total: 38.9ms	remaining: 17.5ms
69:	learn: 8.8177180	total: 39.4ms	remaining: 16.9ms
70:	learn: 8.8134386	total: 40.2ms	remaining: 16.4ms
71:	learn: 8.8085206	total: 40.7ms	remaining: 15.8ms
72:	learn: 8.8043691	total: 41.5ms	remaining: 15.3ms
73:	learn: 8.7991007	total: 42.4ms	remaining: 14.9ms
74:	learn: 8.7945705	total: 42.9ms	remaining: 14.3ms
75:	learn: 8.7895944	total: 44.5ms	remaining: 14ms
76:	learn: 8.7845031	total: 46.7ms	remaining: 14ms
77:	learn: 8.7803960	total: 47.5ms	remaining: 13.4ms
78:	learn: 8.7754260	total: 50.1ms	remaining: 13.3ms
79:	learn: 8.7704042	total: 50.6ms	remaining: 12.7ms
80:	learn: 8.7661220	total: 51.1ms	remaining: 12ms
81:	learn: 8.7618584	total: 51.6ms	remaining: 11.3ms
82:	learn: 8.7569438	total: 52.1ms	remaining: 10.7ms
83:	learn: 8.7525779	total: 52.5ms	remaining: 10ms
84:	learn: 8.7485385	total: 53ms	remaining: 9.36ms
85:	learn: 8.7436154	total: 53.5ms	remaining: 8.71ms
86:	learn: 8.7393884	total: 54ms	remaining: 8.06ms
87:	learn: 8.7353240	total: 54.5ms	remaining: 7.43ms
88:	learn: 8.7305550	total: 55ms	remaining: 6.79ms
89:	learn: 8.7255752	total: 55.5ms	remaining: 6.16ms
90:	learn: 8.7203732	total: 55.9ms	remaining: 5.53ms
91:	learn: 8.7152798	total: 56.4ms	remaining: 4.9ms
92:	learn: 8.7112823	total: 56.8ms	remaining: 4.28ms
93:	learn: 8.7060059	total: 57.3ms	remaining: 3.66ms
94:	learn: 8.7007100	total: 57.8ms	remaining: 3.04ms
95:	learn: 8.6955054	total: 58.2ms	remaining: 2.43ms
96:	learn: 8.6907425	total: 58.7ms	remaining: 1.81ms
97:	learn: 8.6853865	total: 59.2ms	remaining: 1.21ms
98:	learn: 8.6802786	total: 59.6ms	remaining: 602us
99:	learn: 8.6752757	total: 60.1ms	remaining: 0us
0:	learn: 9.1880396	total: 603us	remaining: 59.7ms
1:	learn: 9.1836144	total: 1.15ms	remaining: 56.4ms
2:	learn: 9.1793250	total: 1.62ms	remaining: 52.4ms
3:	learn: 9.1738066	total: 2.13ms	remaining: 51.1ms
4:	learn: 9.1684761	total: 2.62ms	remaining: 49.8ms
5:	learn: 9.1637247	total: 3.1ms	remaining: 48.6ms
6:	learn: 9.1578994	total: 3.58ms	remaining: 47.6ms
7:	learn: 9.1529303	total: 4.06ms	remaining: 46.7ms
8:	learn: 9.1480276	total: 4.56ms	remaining: 46.1ms
9:	learn: 9.1439383	total: 5.04ms	remaining: 45.3ms
10:	learn: 9.1396041	total: 5.51ms	remaining: 44.6ms
11:	learn: 9.1340841	total: 5.97ms	remaining: 43.8ms
12:	learn: 9.1295996	total: 6.46ms	remaining: 43.2ms
13:	learn: 9.1247505	total: 6.92ms	remaining: 42.5ms
14:	learn: 9.1194750	total: 7.39ms	remaining: 41.9ms
15:	learn: 9.1151070	total: 7.85ms	remaining: 41.2ms
16:	learn: 9.1097122	total: 8.35ms	remaining: 40.7ms
17:	learn: 9.1045480	total: 8.81ms	remaining: 40.1ms
18:	learn: 9.0999739	total: 9.28ms	remaining: 39.6ms
19:	learn: 9.0942349	total: 9.75ms	remaining: 39ms
20:	learn: 9.0898712	total: 10.2ms	remaining: 38.5ms
21:	learn: 9.0845073	total: 10.7ms	remaining: 37.9ms
22:	learn: 9.0801180	total: 11.2ms	remaining: 37.4ms
23:	learn: 9.0748382	total: 11.8ms	remaining: 37.4ms
24:	learn: 9.0703753	total: 12.3ms	remaining: 37ms
25:	learn: 9.0663215	total: 12.8ms	remaining: 36.6ms
26:	learn: 9.0621405	total: 13.3ms	remaining: 36ms
27:	learn: 9.0569773	total: 13.8ms	remaining: 35.5ms
28:	learn: 9.0520763	total: 14.3ms	remaining: 35.1ms
29:	learn: 9.0466425	total: 14.8ms	remaining: 34.6ms
30:	learn: 9.0419065	total: 15.3ms	remaining: 34.1ms
31:	learn: 9.0372701	total: 15.8ms	remaining: 33.6ms
32:	learn: 9.0325569	total: 16.3ms	remaining: 33.1ms
33:	learn: 9.0275965	total: 16.8ms	remaining: 32.5ms
34:	learn: 9.0226942	total: 17.4ms	remaining: 32.3ms
35:	learn: 9.0177202	total: 17.9ms	remaining: 31.9ms
36:	learn: 9.0125444	total: 18.4ms	remaining: 31.4ms
37:	learn: 9.0081034	total: 19ms	remaining: 30.9ms
38:	learn: 9.0027331	total: 19.4ms	remaining: 30.4ms
39:	learn: 8.9975900	total: 19.9ms	remaining: 29.9ms
40:	learn: 8.9933910	total: 20.4ms	remaining: 29.4ms
41:	learn: 8.9884693	total: 20.9ms	remaining: 28.9ms
42:	learn: 8.9832720	total: 21.4ms	remaining: 28.3ms
43:	learn: 8.9780710	total: 21.9ms	remaining: 27.8ms
44:	learn: 8.9735252	total: 22.5ms	remaining: 27.4ms
45:	learn: 8.9681705	total: 22.9ms	remaining: 26.9ms
46:	learn: 8.9629133	total: 23.4ms	remaining: 26.4ms
47:	learn: 8.9581496	total: 23.9ms	remaining: 25.9ms
48:	learn: 8.9535751	total: 24.4ms	remaining: 25.4ms
49:	learn: 8.9491942	total: 24.8ms	remaining: 24.8ms
50:	learn: 8.9442233	total: 25.3ms	remaining: 24.3ms
51:	learn: 8.9400078	total: 25.8ms	remaining: 23.8ms
52:	learn: 8.9353345	total: 26.4ms	remaining: 23.4ms
53:	learn: 8.9306406	total: 26.9ms	remaining: 23ms
54:	learn: 8.9258584	total: 27.4ms	remaining: 22.4ms
55:	learn: 8.9206564	total: 28.2ms	remaining: 22.1ms
56:	learn: 8.9164079	total: 28.9ms	remaining: 21.8ms
57:	learn: 8.9114778	total: 29.4ms	remaining: 21.3ms
58:	learn: 8.9063431	total: 29.9ms	remaining: 20.8ms
59:	learn: 8.9013703	total: 30.4ms	remaining: 20.3ms
60:	learn: 8.8962100	total: 30.9ms	remaining: 19.8ms
61:	learn: 8.8910829	total: 31.8ms	remaining: 19.5ms
62:	learn: 8.8871715	total: 32.3ms	remaining: 19ms
63:	learn: 8.8822541	total: 32.8ms	remaining: 18.5ms
64:	learn: 8.8774251	total: 33.6ms	remaining: 18.1ms
65:	learn: 8.8723051	total: 34.2ms	remaining: 17.6ms
66:	learn: 8.8679779	total: 34.7ms	remaining: 17.1ms
67:	learn: 8.8640108	total: 35.2ms	remaining: 16.6ms
68:	learn: 8.8588041	total: 35.7ms	remaining: 16ms
69:	learn: 8.8545881	total: 36.1ms	remaining: 15.5ms
70:	learn: 8.8502251	total: 36.6ms	remaining: 15ms
71:	learn: 8.8459580	total: 37.1ms	remaining: 14.4ms
72:	learn: 8.8421346	total: 37.6ms	remaining: 13.9ms
73:	learn: 8.8370920	total: 38.2ms	remaining: 13.4ms
74:	learn: 8.8324427	total: 38.6ms	remaining: 12.9ms
75:	learn: 8.8275250	total: 39.2ms	remaining: 12.4ms
76:	learn: 8.8222828	total: 39.7ms	remaining: 11.8ms
77:	learn: 8.8181196	total: 40.1ms	remaining: 11.3ms
78:	learn: 8.8133401	total: 40.6ms	remaining: 10.8ms
79:	learn: 8.8084483	total: 41.1ms	remaining: 10.3ms
80:	learn: 8.8037770	total: 41.5ms	remaining: 9.74ms
81:	learn: 8.8000484	total: 42ms	remaining: 9.22ms
82:	learn: 8.7951595	total: 42.5ms	remaining: 8.7ms
83:	learn: 8.7903689	total: 42.9ms	remaining: 8.18ms
84:	learn: 8.7862573	total: 43.4ms	remaining: 7.66ms
85:	learn: 8.7813394	total: 43.9ms	remaining: 7.14ms
86:	learn: 8.7771856	total: 44.3ms	remaining: 6.63ms
87:	learn: 8.7728680	total: 44.8ms	remaining: 6.11ms
88:	learn: 8.7679894	total: 45.3ms	remaining: 5.6ms
89:	learn: 8.7631127	total: 45.7ms	remaining: 5.08ms
90:	learn: 8.7582642	total: 46.2ms	remaining: 4.57ms
91:	learn: 8.7532255	total: 46.7ms	remaining: 4.06ms
92:	learn: 8.7485501	total: 47.2ms	remaining: 3.55ms
93:	learn: 8.7431493	total: 47.6ms	remaining: 3.04ms
94:	learn: 8.7379371	total: 48.1ms	remaining: 2.53ms
95:	learn: 8.7328889	total: 48.5ms	remaining: 2.02ms
96:	learn: 8.7279180	total: 49ms	remaining: 1.51ms
97:	learn: 8.7234965	total: 49.5ms	remaining: 1.01ms
98:	learn: 8.7191701	total: 49.9ms	remaining: 504us
99:	learn: 8.7144070	total: 50.5ms	remaining: 0us
0:	learn: 9.5323674	total: 684us	remaining: 67.7ms
1:	learn: 9.5275116	total: 1.26ms	remaining: 61.7ms
2:	learn: 9.5228525	total: 1.77ms	remaining: 57.3ms
3:	learn: 9.5173493	total: 2.28ms	remaining: 54.7ms
4:	learn: 9.5113124	total: 2.83ms	remaining: 53.7ms
5:	learn: 9.5061108	total: 3.34ms	remaining: 52.4ms
6:	learn: 9.4999676	total: 3.85ms	remaining: 51.1ms
7:	learn: 9.4942376	total: 4.35ms	remaining: 50ms
8:	learn: 9.4886271	total: 4.85ms	remaining: 49.1ms
9:	learn: 9.4836052	total: 5.36ms	remaining: 48.3ms
10:	learn: 9.4787208	total: 5.85ms	remaining: 47.3ms
11:	learn: 9.4725452	total: 6.53ms	remaining: 47.9ms
12:	learn: 9.4668224	total: 7.09ms	remaining: 47.4ms
13:	learn: 9.4615578	total: 7.61ms	remaining: 46.7ms
14:	learn: 9.4555394	total: 8.09ms	remaining: 45.9ms
15:	learn: 9.4503512	total: 8.56ms	remaining: 44.9ms
16:	learn: 9.4441914	total: 9.04ms	remaining: 44.1ms
17:	learn: 9.4385229	total: 9.49ms	remaining: 43.2ms
18:	learn: 9.4335114	total: 9.96ms	remaining: 42.5ms
19:	learn: 9.4272384	total: 10.4ms	remaining: 41.8ms
20:	learn: 9.4226149	total: 10.9ms	remaining: 41.1ms
21:	learn: 9.4166952	total: 11.4ms	remaining: 40.3ms
22:	learn: 9.4123274	total: 11.8ms	remaining: 39.7ms
23:	learn: 9.4072669	total: 12.3ms	remaining: 39ms
24:	learn: 9.4013894	total: 12.8ms	remaining: 38.4ms
25:	learn: 9.3962425	total: 13.3ms	remaining: 37.7ms
26:	learn: 9.3914072	total: 13.7ms	remaining: 37.1ms
27:	learn: 9.3857729	total: 14.2ms	remaining: 36.5ms
28:	learn: 9.3806323	total: 14.7ms	remaining: 36ms
29:	learn: 9.3755548	total: 15.2ms	remaining: 35.4ms
30:	learn: 9.3699779	total: 15.6ms	remaining: 34.8ms
31:	learn: 9.3646424	total: 16.1ms	remaining: 34.2ms
32:	learn: 9.3592827	total: 16.6ms	remaining: 33.6ms
33:	learn: 9.3540145	total: 17ms	remaining: 33ms
34:	learn: 9.3489165	total: 17.5ms	remaining: 32.5ms
35:	learn: 9.3439184	total: 17.9ms	remaining: 31.9ms
36:	learn: 9.3379095	total: 18.4ms	remaining: 31.3ms
37:	learn: 9.3319317	total: 18.8ms	remaining: 30.7ms
38:	learn: 9.3261842	total: 19.3ms	remaining: 30.2ms
39:	learn: 9.3207937	total: 19.7ms	remaining: 29.6ms
40:	learn: 9.3156319	total: 20.2ms	remaining: 29.1ms
41:	learn: 9.3098400	total: 20.7ms	remaining: 28.6ms
42:	learn: 9.3048571	total: 21.1ms	remaining: 28ms
43:	learn: 9.2988524	total: 21.6ms	remaining: 27.5ms
44:	learn: 9.2932187	total: 22.1ms	remaining: 27ms
45:	learn: 9.2871955	total: 22.5ms	remaining: 26.4ms
46:	learn: 9.2815577	total: 23ms	remaining: 25.9ms
47:	learn: 9.2757812	total: 23.5ms	remaining: 25.4ms
48:	learn: 9.2714402	total: 23.9ms	remaining: 24.9ms
49:	learn: 9.2661074	total: 24.4ms	remaining: 24.4ms
50:	learn: 9.2608522	total: 24.9ms	remaining: 23.9ms
51:	learn: 9.2558134	total: 25.3ms	remaining: 23.4ms
52:	learn: 9.2500847	total: 25.8ms	remaining: 22.9ms
53:	learn: 9.2450300	total: 26.3ms	remaining: 22.4ms
54:	learn: 9.2391751	total: 26.8ms	remaining: 21.9ms
55:	learn: 9.2338547	total: 27.3ms	remaining: 21.4ms
56:	learn: 9.2291843	total: 27.7ms	remaining: 20.9ms
57:	learn: 9.2240598	total: 28.2ms	remaining: 20.4ms
58:	learn: 9.2178876	total: 28.7ms	remaining: 19.9ms
59:	learn: 9.2125375	total: 29.2ms	remaining: 19.4ms
60:	learn: 9.2067695	total: 29.6ms	remaining: 19ms
61:	learn: 9.2012304	total: 30.1ms	remaining: 18.5ms
62:	learn: 9.1965104	total: 30.6ms	remaining: 18ms
63:	learn: 9.1909033	total: 31.1ms	remaining: 17.5ms
64:	learn: 9.1860540	total: 31.5ms	remaining: 17ms
65:	learn: 9.1801974	total: 32ms	remaining: 16.5ms
66:	learn: 9.1753601	total: 32.5ms	remaining: 16ms
67:	learn: 9.1707451	total: 33ms	remaining: 15.5ms
68:	learn: 9.1651796	total: 33.4ms	remaining: 15ms
69:	learn: 9.1593275	total: 33.9ms	remaining: 14.5ms
70:	learn: 9.1541044	total: 34.4ms	remaining: 14ms
71:	learn: 9.1490956	total: 34.8ms	remaining: 13.5ms
72:	learn: 9.1444902	total: 35.3ms	remaining: 13.1ms
73:	learn: 9.1388275	total: 35.7ms	remaining: 12.6ms
74:	learn: 9.1336877	total: 36.2ms	remaining: 12.1ms
75:	learn: 9.1281737	total: 36.7ms	remaining: 11.6ms
76:	learn: 9.1226728	total: 37.2ms	remaining: 11.1ms
77:	learn: 9.1175416	total: 37.7ms	remaining: 10.6ms
78:	learn: 9.1121182	total: 38.1ms	remaining: 10.1ms
79:	learn: 9.1073002	total: 38.6ms	remaining: 9.65ms
80:	learn: 9.1020666	total: 39.1ms	remaining: 9.16ms
81:	learn: 9.0974302	total: 39.5ms	remaining: 8.68ms
82:	learn: 9.0918816	total: 40ms	remaining: 8.19ms
83:	learn: 9.0867372	total: 40.5ms	remaining: 7.71ms
84:	learn: 9.0822770	total: 40.9ms	remaining: 7.22ms
85:	learn: 9.0769496	total: 41.4ms	remaining: 6.74ms
86:	learn: 9.0722918	total: 41.9ms	remaining: 6.26ms
87:	learn: 9.0674938	total: 42.3ms	remaining: 5.77ms
88:	learn: 9.0620261	total: 42.8ms	remaining: 5.29ms
89:	learn: 9.0564262	total: 43.3ms	remaining: 4.81ms
90:	learn: 9.0507464	total: 43.7ms	remaining: 4.32ms
91:	learn: 9.0450883	total: 44.2ms	remaining: 3.84ms
92:	learn: 9.0406035	total: 44.6ms	remaining: 3.36ms
93:	learn: 9.0347846	total: 45.1ms	remaining: 2.88ms
94:	learn: 9.0291640	total: 45.6ms	remaining: 2.4ms
95:	learn: 9.0235719	total: 46ms	remaining: 1.92ms
96:	learn: 9.0180747	total: 46.5ms	remaining: 1.44ms
97:	learn: 9.0126331	total: 46.9ms	remaining: 957us
98:	learn: 9.0076141	total: 47.4ms	remaining: 478us
99:	learn: 9.0019925	total: 47.9ms	remaining: 0us
0:	learn: 9.4404550	total: 1.1ms	remaining: 219ms
1:	learn: 9.4359393	total: 2.57ms	remaining: 255ms
2:	learn: 9.4315263	total: 3.7ms	remaining: 243ms
3:	learn: 9.4264543	total: 4.25ms	remaining: 208ms
4:	learn: 9.4210626	total: 4.8ms	remaining: 187ms
5:	learn: 9.4164999	total: 5.28ms	remaining: 171ms
6:	learn: 9.4117637	total: 5.87ms	remaining: 162ms
7:	learn: 9.4063599	total: 6.35ms	remaining: 152ms
8:	learn: 9.4017204	total: 6.91ms	remaining: 147ms
9:	learn: 9.3968014	total: 7.46ms	remaining: 142ms
10:	learn: 9.3920275	total: 7.98ms	remaining: 137ms
11:	learn: 9.3860713	total: 8.5ms	remaining: 133ms
12:	learn: 9.3814622	total: 8.97ms	remaining: 129ms
13:	learn: 9.3763923	total: 9.44ms	remaining: 125ms
14:	learn: 9.3708020	total: 9.9ms	remaining: 122ms
15:	learn: 9.3664089	total: 10.5ms	remaining: 120ms
16:	learn: 9.3610551	total: 11ms	remaining: 118ms
17:	learn: 9.3556010	total: 11.4ms	remaining: 115ms
18:	learn: 9.3509399	total: 11.9ms	remaining: 114ms
19:	learn: 9.3448440	total: 12.4ms	remaining: 111ms
20:	learn: 9.3402492	total: 12.9ms	remaining: 110ms
21:	learn: 9.3346777	total: 13.3ms	remaining: 108ms
22:	learn: 9.3301266	total: 13.8ms	remaining: 106ms
23:	learn: 9.3243818	total: 14.3ms	remaining: 105ms
24:	learn: 9.3198853	total: 14.8ms	remaining: 104ms
25:	learn: 9.3152764	total: 15.3ms	remaining: 102ms
26:	learn: 9.3107707	total: 15.8ms	remaining: 101ms
27:	learn: 9.3053055	total: 16.2ms	remaining: 99.6ms
28:	learn: 9.3005049	total: 16.7ms	remaining: 98.4ms
29:	learn: 9.2949499	total: 17.1ms	remaining: 97.1ms
30:	learn: 9.2897060	total: 17.6ms	remaining: 96ms
31:	learn: 9.2849819	total: 18.1ms	remaining: 94.9ms
32:	learn: 9.2801130	total: 18.5ms	remaining: 93.9ms
33:	learn: 9.2745837	total: 19ms	remaining: 92.8ms
34:	learn: 9.2688848	total: 19.5ms	remaining: 91.8ms
35:	learn: 9.2644117	total: 20ms	remaining: 91ms
36:	learn: 9.2587651	total: 20.4ms	remaining: 90ms
37:	learn: 9.2530627	total: 20.9ms	remaining: 89ms
38:	learn: 9.2473836	total: 21.3ms	remaining: 88.1ms
39:	learn: 9.2418660	total: 21.8ms	remaining: 87.2ms
40:	learn: 9.2371781	total: 22.2ms	remaining: 86.3ms
41:	learn: 9.2317071	total: 22.7ms	remaining: 85.4ms
42:	learn: 9.2265985	total: 23.2ms	remaining: 84.6ms
43:	learn: 9.2209161	total: 23.6ms	remaining: 83.8ms
44:	learn: 9.2161802	total: 24.1ms	remaining: 83ms
45:	learn: 9.2107288	total: 24.6ms	remaining: 82.2ms
46:	learn: 9.2049945	total: 25ms	remaining: 81.4ms
47:	learn: 9.1995920	total: 25.5ms	remaining: 80.7ms
48:	learn: 9.1947413	total: 25.9ms	remaining: 80ms
49:	learn: 9.1907081	total: 26.4ms	remaining: 79.3ms
50:	learn: 9.1855401	total: 26.9ms	remaining: 78.5ms
51:	learn: 9.1808878	total: 27.3ms	remaining: 77.8ms
52:	learn: 9.1755892	total: 27.8ms	remaining: 77.1ms
53:	learn: 9.1705133	total: 28.3ms	remaining: 76.4ms
54:	learn: 9.1647915	total: 28.7ms	remaining: 75.7ms
55:	learn: 9.1604573	total: 29.2ms	remaining: 75.1ms
56:	learn: 9.1560266	total: 29.7ms	remaining: 74.4ms
57:	learn: 9.1501563	total: 30.1ms	remaining: 73.8ms
58:	learn: 9.1447612	total: 30.6ms	remaining: 73.1ms
59:	learn: 9.1390527	total: 31.1ms	remaining: 72.6ms
60:	learn: 9.1337519	total: 31.6ms	remaining: 71.9ms
61:	learn: 9.1282635	total: 32ms	remaining: 71.3ms
62:	learn: 9.1235743	total: 32.5ms	remaining: 70.7ms
63:	learn: 9.1183423	total: 33ms	remaining: 70.1ms
64:	learn: 9.1131488	total: 33.5ms	remaining: 69.5ms
65:	learn: 9.1087126	total: 33.9ms	remaining: 68.9ms
66:	learn: 9.1042612	total: 34.4ms	remaining: 68.3ms
67:	learn: 9.1000396	total: 34.9ms	remaining: 67.7ms
68:	learn: 9.0945814	total: 35.3ms	remaining: 67.1ms
69:	learn: 9.0893834	total: 35.8ms	remaining: 66.5ms
70:	learn: 9.0846453	total: 36.3ms	remaining: 65.9ms
71:	learn: 9.0802644	total: 36.7ms	remaining: 65.3ms
72:	learn: 9.0760468	total: 37.2ms	remaining: 64.7ms
73:	learn: 9.0705798	total: 37.7ms	remaining: 64.1ms
74:	learn: 9.0657098	total: 38.2ms	remaining: 63.6ms
75:	learn: 9.0602213	total: 38.7ms	remaining: 63.1ms
76:	learn: 9.0548490	total: 39.2ms	remaining: 62.6ms
77:	learn: 9.0501523	total: 39.7ms	remaining: 62.1ms
78:	learn: 9.0449220	total: 40.2ms	remaining: 61.5ms
79:	learn: 9.0395808	total: 40.6ms	remaining: 61ms
80:	learn: 9.0346505	total: 41.1ms	remaining: 60.4ms
81:	learn: 9.0307427	total: 41.6ms	remaining: 59.8ms

In [ ]:
assert type(model) == CatBoostRegressor
assert type(grid_search) == GridSearchCV

In [ ]:
# Вывод результатов моделей регрессии

data = [
    ['LinearRegression', f'{LinearRegression_mse}', f'{LinearRegression_best_params}'],
    ['SVR', f'{SVR_mse}', f'{SVR_best_params}'],
    ['DecisionTreeRegressor', f'{DecisionTreeRegressor_mse}', f'{DecisionTreeRegressor_best_params}'],
    ['RandomForestRegressor', f'{RandomForestRegressor_mse}', f'{RandomForestRegressor_best_params}'],
    ['GradientBoostingRegressor', f'{GradientBoostingRegressor_mse}', f'{GradientBoostingRegressor_best_params}'],
    ['AdaBoostRegressor', f'{AdaBoostRegressor_mse}', f'{AdaBoostRegressor_best_params}'],
    ['XGBRegressor', f'{XGBRegressor_mse}', f'{XGBRegressor_best_params}'],
    ['CatBoostRegressor', f'{CatBoostRegressor_mse}', f'{CatBoostRegressor_best_params}']
]


# Создание DataFrame из данных
df = pd.DataFrame(data, columns=['Модель', 'MSE', 'Параметры'], index=range(1, 1 + len(data)))
pd.set_option('display.max_colwidth', None)
# Отображение DataFrame
df.head(len(data))

,Модель,MSE,Параметры
1,LinearRegression,24.818442738481327,{'fit_intercept': True}
2,SVR,13.497844888204211,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}"
3,DecisionTreeRegressor,9.984117647058822,{'max_depth': None}
4,RandomForestRegressor,8.572064308378026,"{'max_depth': 10, 'min_samples_split': 2, 'n_estimators': 200}"
5,GradientBoostingRegressor,6.498597264505265,"{'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}"
6,AdaBoostRegressor,11.358523987100476,"{'learning_rate': 0.1, 'n_estimators': 100}"
7,XGBRegressor,5.988378570059145,"{'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200}"
8,CatBoostRegressor,10.905647311507755,"{'colsample_bylevel': 1.0, 'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 200, 'reg_lambda': 3.0, 'subsample': 1.0}"

# Задача классификации

Мы будем использовать датасет "Bank Marketing". В датасете "Bank Marketing" содержатся данные, связанные с маркетинговыми кампаниями банка. Вот колонки, представленные в датасете "Bank Marketing":

1. **age**: Возраст клиента.

2. **job**: Тип работы клиента.

3. **marital**: Семейное положение клиента.

4. **education**: Образование клиента.

5. **default**: Есть ли у клиента кредитный дефолт (задолженность).

6. **balance**: Баланс на счете клиента.

7. **housing**: Имеет ли клиент ипотеку (жилую недвижимость).

8. **loan**: Имеет ли клиент личный заем.

9. **contact**: Способ связи с клиентом.

10. **day**: День месяца, когда был выполнен последний контакт.

11. **month**: Месяц года, когда был выполнен последний контакт.

12. **duration**: Продолжительность последнего контакта в секундах.

13. **campaign**: Количество контактов, выполненных во время данной кампании.

14. **pdays**: Количество дней, прошедших с момента последнего контакта до предыдущей кампании.

15. **previous**: Количество контактов, выполненных перед текущей кампанией.

16. **poutcome**: Результат предыдущей маркетинговой кампании.

17. **y**: Целевая переменная, которую необходимо предсказать. Например, это может быть информация о том, стал ли клиент подписчиком (1) или нет (0) на определенное предложение банка.

Мы будем использовать 7 моделей классификации и GridSearchCV для подбора параметров:
1. Логистическая регрессия (Logistic Regression): `sklearn.linear_model.LogisticRegression`
2. Метод опорных векторов (Support Vector Machines): `sklearn.svm.SVC`
3. Решающие деревья (Decision Trees): `sklearn.tree.DecisionTreeClassifier`
4. Случайный лес (Random Forest): `sklearn.ensemble.RandomForestClassifier`
5. Градиентный бустинг (Gradient Boosting): `sklearn.ensemble.GradientBoostingClassifier`
6. XGBoost: `xgboost.XGBClassifier`
7. CatBoost: `catboost.CatBoostClassifier`

In [ ]:
# Загрузка данных из CSV файла
data = pd.read_csv("https://www.dropbox.com/scl/fi/ixp788fuekyu1xzn9ehe8/bank_full.csv?rlkey=0q2t7v99qggl4m4qr60p9z2ug&dl=1", delimiter=";")
data.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [ ]:
# Разделение на признаки (X) и целевую переменную (y)
X = data.drop('y', axis=1)
y = data['y'].apply(lambda x: 1 if x=="yes" else 0)


# Разделение на обучающий и тестовый наборы данных
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Определение препроцессора для категориальных и числовых признаков
categorical_features = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']
categorical_transformer = OneHotEncoder(handle_unknown='ignore')
numerical_features = X_train.select_dtypes(include=['int64', 'float64']).columns
numerical_transformer = StandardScaler()

# Объединение препроцессоров
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_features),
        ('num', numerical_transformer, numerical_features)
    ])

# Создание пайплайна для препроцессора
preprocessing_pipeline = Pipeline(steps=[('preprocessor', preprocessor)])

# Применение препроцессора к данным
X_train = preprocessing_pipeline.fit_transform(X_train)
X_test = preprocessing_pipeline.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

"""
Задание 2.1 (1 балл)
Сохраните в переменную model экземпляр класса LogisticRegression без параметров.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model=LogisticRegression()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""
'penalty': ['l1', 'l2']

Параметр 'penalty' отвечает за регуляризацию модели, то есть штраф за сложность модели. Значение 'l1'
соответствует L1-регуляризации (Лассо), которая добавляет штраф, равный абсолютному значению коэффициентов
модели. Значение 'l2' соответствует L2-регуляризации (гребневая регрессия), которая добавляет штраф,
равный квадрату значений коэффициентов модели. Выбор между 'l1' и 'l2' позволяет контролировать влияние
каждого из этих типов регуляризации на модель.

'C': [0.1, 1.0, 10.0]
Параметр 'C' определяет обратную силу регуляризации. Значение 'C' контролирует степень регуляризации:
чем меньше значение 'C', тем сильнее применяется регуляризация, а чем больше значение 'C', тем слабее
регуляризация. Таким образом, параметр 'C' позволяет настраивать баланс между точностью модели на
обучающих данных и ее сложностью, предотвращая переобучение.
"""

params = {
'penalty': ['l1', 'l2'],
'C': [0.1, 1.0, 10.0]
}

# Создание объекта GridSearchCV
"""
Задание 2.2 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='f1_macro'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='f1_macro')


# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров LogisticRegression
LogisticRegression_best_params = grid_search.best_params_
print("LogisticRegression_best_params: ", LogisticRegression_best_params)

# Вычисление F1-меры
LogisticRegression_f1 = f1_score(y_test, y_pred, average='macro')
print("LogisticRegression_f1: ", LogisticRegression_f1)

LogisticRegression_best_params:  {'C': 10.0, 'penalty': 'l2'}
LogisticRegression_f1:  0.6958843399850148

In [ ]:
assert type(model) == LogisticRegression
assert type(grid_search) == GridSearchCV

In [43]:
from sklearn.svm import SVC

"""
Задание 2.3 (1 балл)
Сохраните в переменную model экземпляр класса SVC без параметров.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model=SVC()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""
'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
Параметр 'kernel' определяет тип используемого ядра для построения гиперплоскости. Значение 'linear'
означает линейное ядро, которое строит гиперплоскость с помощью линейной функции. Значение 'poly'
означает полиномиальное ядро, которое строит гиперплоскость с помощью полиномиальной функции.
Значение 'rbf' означает радиальное базисное ядро (RBF), которое строит гиперплоскость с помощью
радиальной базисной функции. Значение 'sigmoid' означает сигмоидное ядро, которое строит гиперплоскость
с помощью сигмоидной функции.

'C': [0.1, 1.0, 10.0]
Параметр 'C' определяет параметр регуляризации модели SVM. Большее значение 'C' означает меньшую
регуляризацию, что может привести к более точной модели на обучающих данных, но также может привести
к переобучению. Меньшее значение 'C' означает большую регуляризацию, что может привести к менее точной
модели, но более устойчивой к шуму и выбросам.

"""

# params = {
#     'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
#     'C': [0.1, 1.0, 10.0]
# }
params = {
    'kernel': ['linear'],
    'C': [1.0]
}

# Создание объекта GridSearchCV
"""
Задание 2.4 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='f1_macro'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='f1_macro')


# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров SVC
SVC_best_params = grid_search.best_params_
print("SVC_best_params: ", SVC_best_params)

# Вычисление F1-меры
SVC_f1 = f1_score(y_test, y_pred, average='macro')
print("SVC_f1: ", SVC_f1)

SVC_best_params:  {'C': 1.0, 'kernel': 'linear'}
SVC_f1:  0.615523472539518

In [44]:
assert type(model) == SVC
assert type(grid_search) == GridSearchCV

In [47]:
from sklearn.tree import DecisionTreeClassifier

"""
Задание 2.5 (1 балл)
Сохраните в переменную model экземпляр класса DecisionTreeClassifier без параметров.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model =DecisionTreeClassifier()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""
'criterion': ['gini', 'entropy']
Параметр 'criterion' определяет критерий, используемый для измерения качества разделения. Значение
'gini' означает использование индекса Джини, который измеряет неопределенность набора данных. Значение
'entropy' означает использование энтропийного критерия, который также измеряет неопределенность набора
данных, но использует логарифмическую шкалу.

'max_depth': [None, 5, 10]
Параметр 'max_depth' определяет максимальную глубину дерева решений. Значение None означает, что глубина
дерева не ограничена. Числовые значения указывают конкретное ограничение на глубину дерева.

"""

params = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 5, 10]
}

# Создание объекта GridSearchCV
"""
Задание 2.6 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='f1_macro'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='f1_macro')



# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров DecisionTreeClassifier
DecisionTreeClassifier_best_params = grid_search.best_params_
print("DecisionTreeClassifier_best_params: ", DecisionTreeClassifier_best_params)

# Вычисление F1-меры
DecisionTreeClassifier_f1 = f1_score(y_test, y_pred, average='macro')
print("DecisionTreeClassifier_f1: ", DecisionTreeClassifier_f1)

DecisionTreeClassifier_best_params:  {'criterion': 'gini', 'max_depth': 10}
DecisionTreeClassifier_f1:  0.7179669831854787

In [48]:
assert type(model) == DecisionTreeClassifier
assert type(grid_search) == GridSearchCV

In [49]:
from sklearn.ensemble import RandomForestClassifier

"""
Задание 2.7 (1 балл)
Сохраните в переменную model экземпляр класса RandomForestClassifier без параметров.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model =RandomForestClassifier()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""
'n_estimators': [100, 200, 300]
Параметр 'n_estimators' определяет количество деревьев в лесу. Большее количество деревьев может повысить
точность модели, но может также увеличить время обучения и инференса.

'max_depth': [None, 5, 10]
Параметр 'max_depth' определяет максимальную глубину дерева решений в лесу. Значение None означает, что
глубина деревьев не ограничена. Числовые значения указывают конкретное ограничение на глубину дерева.

"""

params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 5, 10]
}

# Создание объекта GridSearchCV
"""
Задание 2.8 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='f1_macro'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='f1_macro')



# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров RandomForestClassifier
RandomForestClassifier_best_params = grid_search.best_params_
print("RandomForestClassifier_best_params: ", RandomForestClassifier_best_params)

# Вычисление F1-меры
RandomForestClassifier_f1 = f1_score(y_test, y_pred, average='macro')
print("RandomForestClassifier_f1: ", RandomForestClassifier_f1)

RandomForestClassifier_best_params:  {'max_depth': None, 'n_estimators': 300}
RandomForestClassifier_f1:  0.727653748362312

In [50]:
assert type(model) == RandomForestClassifier
assert type(grid_search) == GridSearchCV

In [51]:
from sklearn.ensemble import GradientBoostingClassifier

"""
Задание 2.9 (1 балл)
Сохраните в переменную model экземпляр класса GradientBoostingClassifier без параметров.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model =GradientBoostingClassifier()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""
'n_estimators': [100, 200, 300]
Параметр 'n_estimators' определяет количество деревьев в градиентном бустинге. Большее количество деревьев
может повысить точность модели, но может также увеличить время обучения и инференса.

'max_depth': [3, 5, 10]
Параметр 'max_depth' определяет максимальную глубину дерева решений в градиентном бустинге. Значение 3, 5
или 10 указывает конкретное ограничение на глубину дерева.

'learning_rate': [0.1, 0.01, 0.001]
Параметр 'learning_rate' определяет скорость обучения модели. Меньшие значения 'learning_rate' могут
требовать большего количества деревьев для достижения высокой точности модели.

"""

# params = {
#     'n_estimators': [100, 200, 300],
#     'max_depth': [3, 5, 10],
#     'learning_rate': [0.1, 0.01, 0.001]
# }

params = {
    'n_estimators': [30, 50, 100],
    'max_depth': [5],
    'learning_rate': [0.1, 0.01]
}

# Создание объекта GridSearchCV
"""
Задание 2.10 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='f1_macro'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='f1_macro')



# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров GradientBoostingClassifier
GradientBoostingClassifier_best_params = grid_search.best_params_
print("GradientBoostingClassifier_best_params: ", GradientBoostingClassifier_best_params)

# Вычисление F1-меры
GradientBoostingClassifier_f1 = f1_score(y_test, y_pred, average='macro')
print("GradientBoostingClassifier_f1: ", GradientBoostingClassifier_f1)

GradientBoostingClassifier_best_params:  {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}
GradientBoostingClassifier_f1:  0.7515066929591387

In [52]:
assert type(model) == GradientBoostingClassifier
assert type(grid_search) == GridSearchCV

In [53]:
import xgboost as xgb

"""
Задание 2.11 (1 балл)
Сохраните в переменную model экземпляр класса xgb.XGBClassifier без параметров.
Пример:
var = ClassExample()
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model =xgb.XGBClassifier()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""
'n_estimators': [100, 200, 300]
Параметр 'n_estimators' определяет количество деревьев в ансамбле. Большее количество деревьев может
улучшить качество модели, но может также увеличить время обучения и инференса.

'max_depth': [3, 5, 10]
Параметр 'max_depth' определяет максимальную глубину дерева. Увеличение глубины дерева может привести к
более сложной модели, которая может переобучиться на тренировочных данных.

'learning_rate': [0.1, 0.01, 0.001]
Параметр 'learning_rate' определяет скорость обучения модели. Меньшие значения 'learning_rate' требуют
большего числа деревьев для достижения хорошей точности модели.

"""

# params = {
#     'n_estimators': [100, 200, 300],
#     'max_depth': [3, 5, 10],
#     'learning_rate': [0.1, 0.01, 0.001]
# }
params = {
    'n_estimators': [30, 50, 100],
    'max_depth': [3, 5],
    'learning_rate': [0.1, 0.01]
}

# Создание объекта GridSearchCV
"""
Задание 2.12 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='f1_macro'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='f1_macro')


# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров XGBClassifier
XGBClassifier_best_params = grid_search.best_params_
print("XGBClassifier_best_params: ", XGBClassifier_best_params)

# Вычисление F1-меры
XGBClassifier_f1 = f1_score(y_test, y_pred, average='macro')
print("XGBClassifier_f1: ", XGBClassifier_f1)

XGBClassifier_best_params:  {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}
XGBClassifier_f1:  0.7526640510574003

In [54]:
assert type(model) == xgb.XGBClassifier
assert type(grid_search) == GridSearchCV

In [55]:
import catboost as cb

"""
Задание 2.13 (1 балл)
Сохраните в переменную model экземпляр класса cb.CatBoostClassifier с параметром silent=True.
Пример:
var = ClassExample(silent=True)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

model =cb.CatBoostClassifier()

# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Определение параметров для GridSearchCV
"""
'n_estimators': [100, 200, 300]
Параметр 'n_estimators' определяет количество деревьев в ансамбле. Большее количество деревьев может
улучшить качество модели, но может также увеличить время обучения и инференса.

'max_depth': [3, 5, 10]
Параметр 'max_depth' определяет максимальную глубину дерева. Увеличение глубины дерева может привести к
более сложной модели, которая может переобучиться на тренировочных данных.

'learning_rate': [0.1, 0.01, 0.001]
Параметр 'learning_rate' определяет скорость обучения модели. Меньшие значения 'learning_rate' требуют
большего числа деревьев для достижения хорошей точности модели.

"""

# params = {
#     'n_estimators': [100, 200, 300],
#     'max_depth': [3, 5, 10],
#     'learning_rate': [0.1, 0.01, 0.001]
# }
params = {
    'n_estimators': [30, 50, 100],
    'max_depth': [3, 5],
    'learning_rate': [0.1, 0.01]
}

# Создание объекта GridSearchCV
"""
Задание 2.14 (1 балл)
Сохраните в переменную grid_search экземпляр класса GridSearchCV со следующими параметрами:
estimator=model
param_grid=params
scoring='f1_macro'
Пример:
var = GridSearchCV(par1=value1, par2=value2, par3=value3)
"""
# НАЧАЛО ВАШЕГО РЕШЕНИЯ

grid_search = GridSearchCV(estimator=model, param_grid=params, scoring='f1_macro')



# КОНЕЦ ВАШЕГО РЕШЕНИЯ

# Обучение модели на обучающих данных
grid_search.fit(X_train, y_train)

# Получение лучшей модели
best_model = grid_search.best_estimator_

# Предсказание на тестовых данных
y_pred = best_model.predict(X_test)

# Получение лучших параметров CatBoostClassifier
CatBoostClassifier_best_params = grid_search.best_params_
print("CatBoostClassifier_best_params: ", CatBoostClassifier_best_params)

# Вычисление F1-меры
CatBoostClassifier_f1 = f1_score(y_test, y_pred, average='macro')
print("CatBoostClassifier_f1: ", CatBoostClassifier_f1)

0:	learn: 0.5781255	total: 22.9ms	remaining: 665ms
1:	learn: 0.5098579	total: 30.3ms	remaining: 425ms
2:	learn: 0.4495349	total: 36.6ms	remaining: 330ms
3:	learn: 0.4024521	total: 42.5ms	remaining: 276ms
4:	learn: 0.3659843	total: 48.4ms	remaining: 242ms
5:	learn: 0.3438051	total: 54.5ms	remaining: 218ms
6:	learn: 0.3259682	total: 60.1ms	remaining: 197ms
7:	learn: 0.3148287	total: 65.5ms	remaining: 180ms
8:	learn: 0.3020807	total: 71.2ms	remaining: 166ms
9:	learn: 0.2922750	total: 77.5ms	remaining: 155ms
10:	learn: 0.2850913	total: 83.4ms	remaining: 144ms
11:	learn: 0.2782772	total: 89.2ms	remaining: 134ms
12:	learn: 0.2708119	total: 95.9ms	remaining: 125ms
13:	learn: 0.2669537	total: 102ms	remaining: 117ms
14:	learn: 0.2642846	total: 107ms	remaining: 107ms
15:	learn: 0.2613832	total: 114ms	remaining: 99.6ms
16:	learn: 0.2581606	total: 120ms	remaining: 91.8ms
17:	learn: 0.2537603	total: 127ms	remaining: 84.4ms
18:	learn: 0.2507729	total: 133ms	remaining: 76.9ms
19:	learn: 0.2495842	total: 139ms	remaining: 69.4ms
20:	learn: 0.2476414	total: 144ms	remaining: 61.8ms
21:	learn: 0.2459511	total: 150ms	remaining: 54.6ms
22:	learn: 0.2449990	total: 156ms	remaining: 47.6ms
23:	learn: 0.2428936	total: 162ms	remaining: 40.5ms
24:	learn: 0.2415478	total: 168ms	remaining: 33.6ms
25:	learn: 0.2408451	total: 174ms	remaining: 26.8ms
26:	learn: 0.2399183	total: 180ms	remaining: 20ms
27:	learn: 0.2392788	total: 186ms	remaining: 13.3ms
28:	learn: 0.2381363	total: 192ms	remaining: 6.62ms
29:	learn: 0.2371306	total: 198ms	remaining: 0us
0:	learn: 0.5853936	total: 7.07ms	remaining: 205ms
1:	learn: 0.5098535	total: 13.2ms	remaining: 184ms
2:	learn: 0.4544772	total: 19.5ms	remaining: 176ms
3:	learn: 0.4094326	total: 26ms	remaining: 169ms
4:	learn: 0.3722133	total: 31.8ms	remaining: 159ms
5:	learn: 0.3477712	total: 38.4ms	remaining: 154ms
6:	learn: 0.3311222	total: 44.8ms	remaining: 147ms
7:	learn: 0.3142215	total: 51.4ms	remaining: 141ms
8:	learn: 0.2999168	total: 61.5ms	remaining: 143ms
9:	learn: 0.2920100	total: 69.3ms	remaining: 139ms
10:	learn: 0.2813630	total: 77ms	remaining: 133ms
11:	learn: 0.2767317	total: 84.4ms	remaining: 127ms
12:	learn: 0.2711239	total: 92.2ms	remaining: 121ms
13:	learn: 0.2663648	total: 101ms	remaining: 115ms
14:	learn: 0.2631600	total: 110ms	remaining: 110ms
15:	learn: 0.2598454	total: 121ms	remaining: 106ms
16:	learn: 0.2574618	total: 130ms	remaining: 99.1ms
17:	learn: 0.2538894	total: 137ms	remaining: 91.1ms
18:	learn: 0.2522940	total: 143ms	remaining: 82.9ms
19:	learn: 0.2511342	total: 149ms	remaining: 74.6ms
20:	learn: 0.2498488	total: 157ms	remaining: 67.3ms
21:	learn: 0.2480065	total: 164ms	remaining: 59.6ms
22:	learn: 0.2453893	total: 170ms	remaining: 51.8ms
23:	learn: 0.2433176	total: 177ms	remaining: 44.3ms
24:	learn: 0.2424950	total: 184ms	remaining: 36.7ms
25:	learn: 0.2412081	total: 190ms	remaining: 29.2ms
26:	learn: 0.2400878	total: 195ms	remaining: 21.7ms
27:	learn: 0.2394653	total: 201ms	remaining: 14.3ms
28:	learn: 0.2385201	total: 208ms	remaining: 7.16ms
29:	learn: 0.2376777	total: 216ms	remaining: 0us
0:	learn: 0.5757315	total: 6.79ms	remaining: 197ms
1:	learn: 0.5052722	total: 12.5ms	remaining: 175ms
2:	learn: 0.4514051	total: 18.6ms	remaining: 167ms
3:	learn: 0.4071327	total: 24.5ms	remaining: 159ms
4:	learn: 0.3753188	total: 30ms	remaining: 150ms
5:	learn: 0.3520166	total: 36.1ms	remaining: 145ms
6:	learn: 0.3295680	total: 44.1ms	remaining: 145ms
7:	learn: 0.3164472	total: 50.8ms	remaining: 140ms
8:	learn: 0.3015944	total: 56.7ms	remaining: 132ms
9:	learn: 0.2912673	total: 63ms	remaining: 126ms
10:	learn: 0.2853546	total: 69.1ms	remaining: 119ms
11:	learn: 0.2751384	total: 75.1ms	remaining: 113ms
12:	learn: 0.2712599	total: 81.3ms	remaining: 106ms
13:	learn: 0.2678991	total: 90.9ms	remaining: 104ms
14:	learn: 0.2627924	total: 97.7ms	remaining: 97.7ms
15:	learn: 0.2600969	total: 103ms	remaining: 90.4ms
16:	learn: 0.2559487	total: 110ms	remaining: 83.8ms
17:	learn: 0.2544297	total: 115ms	remaining: 76.6ms
18:	learn: 0.2509344	total: 121ms	remaining: 70.1ms
19:	learn: 0.2491017	total: 127ms	remaining: 63.6ms
20:	learn: 0.2473168	total: 133ms	remaining: 57.1ms
21:	learn: 0.2460197	total: 139ms	remaining: 50.4ms
22:	learn: 0.2448486	total: 145ms	remaining: 44.1ms
23:	learn: 0.2434724	total: 151ms	remaining: 37.8ms
24:	learn: 0.2426056	total: 158ms	remaining: 31.6ms
25:	learn: 0.2418507	total: 163ms	remaining: 25.1ms
26:	learn: 0.2402898	total: 169ms	remaining: 18.8ms
27:	learn: 0.2385994	total: 175ms	remaining: 12.5ms
28:	learn: 0.2378890	total: 182ms	remaining: 6.26ms
29:	learn: 0.2367027	total: 188ms	remaining: 0us
0:	learn: 0.5768870	total: 9.51ms	remaining: 276ms
1:	learn: 0.5055833	total: 15.5ms	remaining: 217ms
2:	learn: 0.4512995	total: 21.7ms	remaining: 196ms
3:	learn: 0.4076378	total: 28.1ms	remaining: 182ms
4:	learn: 0.3755978	total: 33.8ms	remaining: 169ms
5:	learn: 0.3511589	total: 40ms	remaining: 160ms
6:	learn: 0.3290166	total: 45.7ms	remaining: 150ms
7:	learn: 0.3161693	total: 52.1ms	remaining: 143ms
8:	learn: 0.3060825	total: 58.5ms	remaining: 136ms
9:	learn: 0.2972668	total: 64.9ms	remaining: 130ms
10:	learn: 0.2863381	total: 71.3ms	remaining: 123ms
11:	learn: 0.2774558	total: 77.2ms	remaining: 116ms
12:	learn: 0.2704457	total: 82.8ms	remaining: 108ms
13:	learn: 0.2667947	total: 88.6ms	remaining: 101ms
14:	learn: 0.2635452	total: 94.3ms	remaining: 94.3ms
15:	learn: 0.2605582	total: 101ms	remaining: 88ms
16:	learn: 0.2580904	total: 106ms	remaining: 81.4ms
17:	learn: 0.2544820	total: 112ms	remaining: 75ms
18:	learn: 0.2512510	total: 119ms	remaining: 68.7ms
19:	learn: 0.2499743	total: 125ms	remaining: 62.5ms
20:	learn: 0.2482014	total: 131ms	remaining: 56.1ms
21:	learn: 0.2461226	total: 137ms	remaining: 49.6ms
22:	learn: 0.2451110	total: 143ms	remaining: 43.4ms
23:	learn: 0.2434084	total: 149ms	remaining: 37.3ms
24:	learn: 0.2421936	total: 155ms	remaining: 30.9ms
25:	learn: 0.2415724	total: 161ms	remaining: 24.7ms
26:	learn: 0.2402877	total: 167ms	remaining: 18.6ms
27:	learn: 0.2392066	total: 173ms	remaining: 12.3ms
28:	learn: 0.2386546	total: 179ms	remaining: 6.17ms
29:	learn: 0.2377656	total: 184ms	remaining: 0us
0:	learn: 0.5777124	total: 7.36ms	remaining: 214ms
1:	learn: 0.5075129	total: 13.7ms	remaining: 192ms
2:	learn: 0.4482314	total: 19.7ms	remaining: 177ms
3:	learn: 0.4018723	total: 25.8ms	remaining: 167ms
4:	learn: 0.3731677	total: 31.9ms	remaining: 159ms
5:	learn: 0.3438942	total: 37.9ms	remaining: 152ms
6:	learn: 0.3234739	total: 43.6ms	remaining: 143ms
7:	learn: 0.3101025	total: 50ms	remaining: 138ms
8:	learn: 0.2977200	total: 56.1ms	remaining: 131ms
9:	learn: 0.2869419	total: 62ms	remaining: 124ms
10:	learn: 0.2816549	total: 67.6ms	remaining: 117ms
11:	learn: 0.2768885	total: 74.3ms	remaining: 111ms
12:	learn: 0.2710633	total: 83.7ms	remaining: 109ms
13:	learn: 0.2675860	total: 91.4ms	remaining: 104ms
14:	learn: 0.2626188	total: 98.9ms	remaining: 98.9ms
15:	learn: 0.2605861	total: 108ms	remaining: 94.2ms
16:	learn: 0.2580631	total: 115ms	remaining: 88.1ms
17:	learn: 0.2565970	total: 125ms	remaining: 83.3ms
18:	learn: 0.2537682	total: 133ms	remaining: 76.9ms
19:	learn: 0.2518479	total: 140ms	remaining: 70ms
20:	learn: 0.2507620	total: 147ms	remaining: 63ms
21:	learn: 0.2483331	total: 153ms	remaining: 55.6ms
22:	learn: 0.2465739	total: 159ms	remaining: 48.3ms
23:	learn: 0.2448367	total: 165ms	remaining: 41.2ms
24:	learn: 0.2431542	total: 171ms	remaining: 34.2ms
25:	learn: 0.2425243	total: 176ms	remaining: 27.1ms
26:	learn: 0.2416345	total: 182ms	remaining: 20.2ms
27:	learn: 0.2407723	total: 188ms	remaining: 13.4ms
28:	learn: 0.2393152	total: 194ms	remaining: 6.7ms
29:	learn: 0.2386492	total: 200ms	remaining: 0us
0:	learn: 0.5781255	total: 6.49ms	remaining: 318ms
1:	learn: 0.5098579	total: 12.9ms	remaining: 309ms
2:	learn: 0.4495349	total: 18.8ms	remaining: 294ms
3:	learn: 0.4024521	total: 24.7ms	remaining: 284ms
4:	learn: 0.3659843	total: 30.6ms	remaining: 275ms
5:	learn: 0.3438051	total: 36.5ms	remaining: 268ms
6:	learn: 0.3259682	total: 42ms	remaining: 258ms
7:	learn: 0.3148287	total: 47.3ms	remaining: 248ms
8:	learn: 0.3020807	total: 53.2ms	remaining: 242ms
9:	learn: 0.2922750	total: 59.6ms	remaining: 238ms
10:	learn: 0.2850913	total: 68.2ms	remaining: 242ms
11:	learn: 0.2782772	total: 74.7ms	remaining: 237ms
12:	learn: 0.2708119	total: 81.1ms	remaining: 231ms
13:	learn: 0.2669537	total: 87.4ms	remaining: 225ms
14:	learn: 0.2642846	total: 92.9ms	remaining: 217ms
15:	learn: 0.2613832	total: 99.3ms	remaining: 211ms
16:	learn: 0.2581606	total: 106ms	remaining: 205ms
17:	learn: 0.2537603	total: 112ms	remaining: 199ms
18:	learn: 0.2507729	total: 119ms	remaining: 194ms
19:	learn: 0.2495842	total: 125ms	remaining: 187ms
20:	learn: 0.2476414	total: 130ms	remaining: 180ms
21:	learn: 0.2459511	total: 136ms	remaining: 173ms
22:	learn: 0.2449990	total: 142ms	remaining: 167ms
23:	learn: 0.2428936	total: 148ms	remaining: 160ms
24:	learn: 0.2415478	total: 154ms	remaining: 154ms
25:	learn: 0.2408451	total: 160ms	remaining: 148ms
26:	learn: 0.2399183	total: 165ms	remaining: 141ms
27:	learn: 0.2392788	total: 171ms	remaining: 135ms
28:	learn: 0.2381363	total: 177ms	remaining: 128ms
29:	learn: 0.2371306	total: 183ms	remaining: 122ms
30:	learn: 0.2365244	total: 190ms	remaining: 116ms
31:	learn: 0.2354907	total: 196ms	remaining: 110ms
32:	learn: 0.2349303	total: 202ms	remaining: 104ms
33:	learn: 0.2333747	total: 211ms	remaining: 99.3ms
34:	learn: 0.2325312	total: 217ms	remaining: 93.2ms
35:	learn: 0.2320547	total: 223ms	remaining: 86.9ms
36:	learn: 0.2311340	total: 230ms	remaining: 80.7ms
37:	learn: 0.2302910	total: 235ms	remaining: 74.3ms
38:	learn: 0.2297506	total: 241ms	remaining: 68.1ms
39:	learn: 0.2289701	total: 248ms	remaining: 61.9ms
40:	learn: 0.2283022	total: 253ms	remaining: 55.6ms
41:	learn: 0.2279119	total: 260ms	remaining: 49.5ms
42:	learn: 0.2274430	total: 265ms	remaining: 43.2ms
43:	learn: 0.2271136	total: 271ms	remaining: 36.9ms
44:	learn: 0.2265311	total: 277ms	remaining: 30.8ms
45:	learn: 0.2262558	total: 283ms	remaining: 24.6ms
46:	learn: 0.2258733	total: 289ms	remaining: 18.4ms
47:	learn: 0.2255730	total: 295ms	remaining: 12.3ms
48:	learn: 0.2251465	total: 301ms	remaining: 6.14ms
49:	learn: 0.2248803	total: 307ms	remaining: 0us
0:	learn: 0.5853936	total: 7.36ms	remaining: 360ms
1:	learn: 0.5098535	total: 13.2ms	remaining: 317ms
2:	learn: 0.4544772	total: 19.4ms	remaining: 304ms
3:	learn: 0.4094326	total: 25.5ms	remaining: 293ms
4:	learn: 0.3722133	total: 31ms	remaining: 279ms
5:	learn: 0.3477712	total: 37.1ms	remaining: 272ms
6:	learn: 0.3311222	total: 43.3ms	remaining: 266ms
7:	learn: 0.3142215	total: 49.7ms	remaining: 261ms
8:	learn: 0.2999168	total: 55.8ms	remaining: 254ms
9:	learn: 0.2920100	total: 62.2ms	remaining: 249ms
10:	learn: 0.2813630	total: 68.7ms	remaining: 244ms
11:	learn: 0.2767317	total: 74.8ms	remaining: 237ms
12:	learn: 0.2711239	total: 80.6ms	remaining: 230ms
13:	learn: 0.2663648	total: 86.8ms	remaining: 223ms
14:	learn: 0.2631600	total: 92.3ms	remaining: 215ms
15:	learn: 0.2598454	total: 98.6ms	remaining: 210ms
16:	learn: 0.2574618	total: 105ms	remaining: 203ms
17:	learn: 0.2538894	total: 111ms	remaining: 197ms
18:	learn: 0.2522940	total: 117ms	remaining: 191ms
19:	learn: 0.2511342	total: 123ms	remaining: 184ms
20:	learn: 0.2498488	total: 129ms	remaining: 178ms
21:	learn: 0.2480065	total: 135ms	remaining: 172ms
22:	learn: 0.2453893	total: 140ms	remaining: 165ms
23:	learn: 0.2433176	total: 147ms	remaining: 159ms
24:	learn: 0.2424950	total: 153ms	remaining: 153ms
25:	learn: 0.2412081	total: 159ms	remaining: 146ms
26:	learn: 0.2400878	total: 164ms	remaining: 140ms
27:	learn: 0.2394653	total: 170ms	remaining: 133ms
28:	learn: 0.2385201	total: 175ms	remaining: 127ms
29:	learn: 0.2376777	total: 182ms	remaining: 121ms
30:	learn: 0.2371225	total: 188ms	remaining: 115ms
31:	learn: 0.2363556	total: 194ms	remaining: 109ms
32:	learn: 0.2356227	total: 200ms	remaining: 103ms
33:	learn: 0.2340097	total: 211ms	remaining: 99.3ms
34:	learn: 0.2331585	total: 218ms	remaining: 93.6ms
35:	learn: 0.2326935	total: 225ms	remaining: 87.4ms
36:	learn: 0.2319389	total: 232ms	remaining: 81.6ms
37:	learn: 0.2314492	total: 238ms	remaining: 75ms
38:	learn: 0.2310814	total: 243ms	remaining: 68.6ms
39:	learn: 0.2305786	total: 249ms	remaining: 62.3ms
40:	learn: 0.2300892	total: 256ms	remaining: 56.2ms
41:	learn: 0.2293839	total: 262ms	remaining: 49.9ms
42:	learn: 0.2287449	total: 268ms	remaining: 43.7ms
43:	learn: 0.2282898	total: 275ms	remaining: 37.5ms
44:	learn: 0.2275922	total: 281ms	remaining: 31.2ms
45:	learn: 0.2272707	total: 287ms	remaining: 25ms
46:	learn: 0.2266911	total: 294ms	remaining: 18.7ms
47:	learn: 0.2264010	total: 299ms	remaining: 12.4ms
48:	learn: 0.2260896	total: 305ms	remaining: 6.21ms
49:	learn: 0.2258435	total: 311ms	remaining: 0us
0:	learn: 0.5757315	total: 7.86ms	remaining: 385ms
1:	learn: 0.5052722	total: 14.9ms	remaining: 357ms
2:	learn: 0.4514051	total: 21.1ms	remaining: 331ms
3:	learn: 0.4071327	total: 27.1ms	remaining: 312ms
4:	learn: 0.3753188	total: 32.8ms	remaining: 295ms
5:	learn: 0.3520166	total: 39ms	remaining: 286ms
6:	learn: 0.3295680	total: 45.1ms	remaining: 277ms
7:	learn: 0.3164472	total: 51.6ms	remaining: 271ms
8:	learn: 0.3015944	total: 57.5ms	remaining: 262ms
9:	learn: 0.2912673	total: 63.6ms	remaining: 254ms
10:	learn: 0.2853546	total: 70.1ms	remaining: 248ms
11:	learn: 0.2751384	total: 76.1ms	remaining: 241ms
12:	learn: 0.2712599	total: 82.3ms	remaining: 234ms
13:	learn: 0.2678991	total: 88.5ms	remaining: 228ms
14:	learn: 0.2627924	total: 94.3ms	remaining: 220ms
15:	learn: 0.2600969	total: 100ms	remaining: 213ms
16:	learn: 0.2559487	total: 106ms	remaining: 207ms
17:	learn: 0.2544297	total: 112ms	remaining: 199ms
18:	learn: 0.2509344	total: 118ms	remaining: 193ms
19:	learn: 0.2491017	total: 128ms	remaining: 192ms
20:	learn: 0.2473168	total: 134ms	remaining: 186ms
21:	learn: 0.2460197	total: 140ms	remaining: 178ms
22:	learn: 0.2448486	total: 146ms	remaining: 171ms
23:	learn: 0.2434724	total: 152ms	remaining: 165ms
24:	learn: 0.2426056	total: 158ms	remaining: 158ms
25:	learn: 0.2418507	total: 164ms	remaining: 151ms
26:	learn: 0.2402898	total: 170ms	remaining: 145ms
27:	learn: 0.2385994	total: 176ms	remaining: 138ms
28:	learn: 0.2378890	total: 182ms	remaining: 132ms
29:	learn: 0.2367027	total: 189ms	remaining: 126ms
30:	learn: 0.2353978	total: 195ms	remaining: 120ms
31:	learn: 0.2349266	total: 201ms	remaining: 113ms
32:	learn: 0.2344921	total: 210ms	remaining: 108ms
33:	learn: 0.2330448	total: 219ms	remaining: 103ms
34:	learn: 0.2326337	total: 225ms	remaining: 96.5ms
35:	learn: 0.2320765	total: 232ms	remaining: 90.2ms
36:	learn: 0.2317073	total: 238ms	remaining: 83.7ms
37:	learn: 0.2312611	total: 245ms	remaining: 77.3ms
38:	learn: 0.2304369	total: 251ms	remaining: 70.7ms
39:	learn: 0.2295471	total: 257ms	remaining: 64.2ms
40:	learn: 0.2292530	total: 263ms	remaining: 57.8ms
41:	learn: 0.2287815	total: 270ms	remaining: 51.4ms
42:	learn: 0.2281933	total: 276ms	remaining: 44.9ms
43:	learn: 0.2276402	total: 282ms	remaining: 38.4ms
44:	learn: 0.2272677	total: 289ms	remaining: 32.1ms
45:	learn: 0.2264622	total: 295ms	remaining: 25.6ms
46:	learn: 0.2258764	total: 301ms	remaining: 19.2ms
47:	learn: 0.2255711	total: 308ms	remaining: 12.8ms
48:	learn: 0.2251413	total: 314ms	remaining: 6.41ms
49:	learn: 0.2247047	total: 320ms	remaining: 0us
0:	learn: 0.5768870	total: 6.59ms	remaining: 323ms
1:	learn: 0.5055833	total: 13.1ms	remaining: 314ms
2:	learn: 0.4512995	total: 19.5ms	remaining: 305ms
3:	learn: 0.4076378	total: 25.4ms	remaining: 292ms
4:	learn: 0.3755978	total: 30.9ms	remaining: 278ms
5:	learn: 0.3511589	total: 37.1ms	remaining: 272ms
6:	learn: 0.3290166	total: 42.7ms	remaining: 262ms
7:	learn: 0.3161693	total: 48.9ms	remaining: 257ms
8:	learn: 0.3060825	total: 55.2ms	remaining: 251ms
9:	learn: 0.2972668	total: 61.5ms	remaining: 246ms
10:	learn: 0.2863381	total: 67.8ms	remaining: 241ms
11:	learn: 0.2774558	total: 73.8ms	remaining: 234ms
12:	learn: 0.2704457	total: 79.6ms	remaining: 226ms
13:	learn: 0.2667947	total: 85.5ms	remaining: 220ms
14:	learn: 0.2635452	total: 91.4ms	remaining: 213ms
15:	learn: 0.2605582	total: 97.7ms	remaining: 208ms
16:	learn: 0.2580904	total: 104ms	remaining: 201ms
17:	learn: 0.2544820	total: 110ms	remaining: 195ms
18:	learn: 0.2512510	total: 116ms	remaining: 189ms
19:	learn: 0.2499743	total: 122ms	remaining: 184ms
20:	learn: 0.2482014	total: 129ms	remaining: 177ms
21:	learn: 0.2461226	total: 135ms	remaining: 171ms
22:	learn: 0.2451110	total: 141ms	remaining: 165ms
23:	learn: 0.2434084	total: 147ms	remaining: 160ms
24:	learn: 0.2421936	total: 153ms	remaining: 153ms
25:	learn: 0.2415724	total: 159ms	remaining: 147ms
26:	learn: 0.2402877	total: 165ms	remaining: 141ms
27:	learn: 0.2392066	total: 171ms	remaining: 135ms
28:	learn: 0.2386546	total: 178ms	remaining: 129ms
29:	learn: 0.2377656	total: 183ms	remaining: 122ms
30:	learn: 0.2370829	total: 189ms	remaining: 116ms
31:	learn: 0.2361792	total: 195ms	remaining: 109ms
32:	learn: 0.2355322	total: 201ms	remaining: 103ms
33:	learn: 0.2350859	total: 209ms	remaining: 98.6ms
34:	learn: 0.2342821	total: 216ms	remaining: 92.5ms
35:	learn: 0.2325418	total: 222ms	remaining: 86.4ms
36:	learn: 0.2309552	total: 228ms	remaining: 80.3ms
37:	learn: 0.2305148	total: 234ms	remaining: 74ms
38:	learn: 0.2300106	total: 241ms	remaining: 67.8ms
39:	learn: 0.2293831	total: 246ms	remaining: 61.5ms
40:	learn: 0.2287968	total: 252ms	remaining: 55.3ms
41:	learn: 0.2283169	total: 258ms	remaining: 49.2ms
42:	learn: 0.2279822	total: 264ms	remaining: 42.9ms
43:	learn: 0.2276996	total: 270ms	remaining: 36.8ms
44:	learn: 0.2270461	total: 276ms	remaining: 30.6ms
45:	learn: 0.2266440	total: 281ms	remaining: 24.5ms
46:	learn: 0.2263029	total: 287ms	remaining: 18.3ms
47:	learn: 0.2258953	total: 294ms	remaining: 12.2ms
48:	learn: 0.2252833	total: 300ms	remaining: 6.12ms
49:	learn: 0.2249915	total: 306ms	remaining: 0us
0:	learn: 0.5777124	total: 6.44ms	remaining: 315ms
1:	learn: 0.5075129	total: 12.4ms	remaining: 298ms
2:	learn: 0.4482314	total: 18.4ms	remaining: 288ms
3:	learn: 0.4018723	total: 25.7ms	remaining: 295ms
4:	learn: 0.3731677	total: 32.7ms	remaining: 294ms
5:	learn: 0.3438942	total: 38.7ms	remaining: 284ms
6:	learn: 0.3234739	total: 44.6ms	remaining: 274ms
7:	learn: 0.3101025	total: 53.1ms	remaining: 279ms
8:	learn: 0.2977200	total: 59.9ms	remaining: 273ms
9:	learn: 0.2869419	total: 66.2ms	remaining: 265ms
10:	learn: 0.2816549	total: 72.5ms	remaining: 257ms
11:	learn: 0.2768885	total: 78.9ms	remaining: 250ms
12:	learn: 0.2710633	total: 85.4ms	remaining: 243ms
13:	learn: 0.2675860	total: 92ms	remaining: 237ms
14:	learn: 0.2626188	total: 98.5ms	remaining: 230ms
15:	learn: 0.2605861	total: 105ms	remaining: 223ms
16:	learn: 0.2580631	total: 111ms	remaining: 215ms
17:	learn: 0.2565970	total: 117ms	remaining: 208ms
18:	learn: 0.2537682	total: 123ms	remaining: 201ms
19:	learn: 0.2518479	total: 129ms	remaining: 194ms
20:	learn: 0.2507620	total: 135ms	remaining: 186ms
21:	learn: 0.2483331	total: 140ms	remaining: 179ms
22:	learn: 0.2465739	total: 146ms	remaining: 172ms
23:	learn: 0.2448367	total: 153ms	remaining: 165ms
24:	learn: 0.2431542	total: 158ms	remaining: 158ms
25:	learn: 0.2425243	total: 164ms	remaining: 151ms
26:	learn: 0.2416345	total: 173ms	remaining: 147ms
27:	learn: 0.2407723	total: 179ms	remaining: 141ms
28:	learn: 0.2393152	total: 185ms	remaining: 134ms
29:	learn: 0.2386492	total: 191ms	remaining: 128ms
30:	learn: 0.2377008	total: 197ms	remaining: 121ms
31:	learn: 0.2359003	total: 207ms	remaining: 117ms
32:	learn: 0.2354356	total: 214ms	remaining: 110ms
33:	learn: 0.2341555	total: 220ms	remaining: 103ms
34:	learn: 0.2336746	total: 226ms	remaining: 97ms
35:	learn: 0.2328102	total: 232ms	remaining: 90.2ms
36:	learn: 0.2323662	total: 238ms	remaining: 83.5ms
37:	learn: 0.2316729	total: 244ms	remaining: 77ms
38:	learn: 0.2312137	total: 249ms	remaining: 70.3ms

In [56]:
assert type(model) == cb.CatBoostClassifier
assert type(grid_search) == GridSearchCV

In [57]:
# Вывод результатов моделей классификации
data = [
    ['LogisticRegression', f'{LogisticRegression_f1}', f'{LogisticRegression_best_params}'],
    ['SVC', f'{SVC_f1}', f'{SVC_best_params}'],
    ['DecisionTreeClassifier', f'{DecisionTreeClassifier_f1}', f'{DecisionTreeClassifier_best_params}'],
    ['RandomForestClassifier', f'{RandomForestClassifier_f1}', f'{RandomForestClassifier_best_params}'],
    ['GradientBoostingClassifier', f'{GradientBoostingClassifier_f1}', f'{GradientBoostingClassifier_best_params}'],
    ['XGBClassifier', f'{XGBClassifier_f1}', f'{XGBClassifier_best_params}'],
    ['CatBoostClassifier', f'{CatBoostClassifier_f1}', f'{CatBoostClassifier_best_params}']
]


# Создание DataFrame из данных
df = pd.DataFrame(data, columns=['Модель', 'F1', 'Параметры'], index=range(1, 1 + len(data)))
pd.set_option('display.max_colwidth', None)
# Отображение DataFrame
df.head(len(data))

,Модель,F1,Параметры
1,LogisticRegression,0.6958843399850148,"{'C': 10.0, 'penalty': 'l2'}"
2,SVC,0.615523472539518,"{'C': 1.0, 'kernel': 'linear'}"
3,DecisionTreeClassifier,0.7179669831854787,"{'criterion': 'gini', 'max_depth': 10}"
4,RandomForestClassifier,0.727653748362312,"{'max_depth': None, 'n_estimators': 300}"
5,GradientBoostingClassifier,0.7515066929591387,"{'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}"
6,XGBClassifier,0.7526640510574003,"{'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}"
7,CatBoostClassifier,0.7402099565852949,"{'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100}"